### ISSUE TITLE
DestinationUV uniform doesn't scale with scene on render

### ISSUE THREAD

**Issue by HikariIsChillin** [motion-canvas/motion-canvas#1013]
**Describe the bug**
If a shader uses destinationUV and you try to render it in a scale different from 1.0x, the uniform doesn't scale with the scene

**To Reproduce**
Just add a shader that uses destinationUV to anything and render with a different scale, this is the simplest example:
```tsx
import { makeScene2D } from '@motion-canvas/2d'

import destinationUVbug from '../shaders/destinationUVbug.glsl'

export default makeScene2D(function* (view) {
	view.shaders(destinationUVbug)
})
```

```glsl
// destinationUVbug.glsl
#version 300 es
precision highp float;

#include "@motion-canvas/core/shaders/common.glsl"

void main() {
    outColor = vec4(floor(destinationUV * 10.) / 10., 0., 1.);
}
```

**Expected behavior**
The UV should scale with the render

**Package versions:**
*Click on the version in the bottom right corner to copy the versions*

- core: ^3.15.1
- ui: ^3.15.1

**Comment by HikariIsChillin** [comment]
Same frame rendered in 0.25x, 0.5x, 1.0x and 2.0x scale:
![004639_0 25x](https://github.com/motion-canvas/motion-canvas/assets/131830820/940caaf2-2955-45a2-aeb8-f80a1e806cb4)
![004639_0 5x](https://github.com/motion-canvas/motion-canvas/assets/131830820/7ce6b1de-34ca-4303-b603-c0700206ac50)
![004639_1 0x](https://github.com/motion-canvas/motion-canvas/assets/131830820/88686da1-9ad4-4c82-854d-feb19036ee84)
![004639_2 0x](https://github.com/motion-canvas/motion-canvas/assets/131830820/8ab92092-9644-4af1-a519-ee5da6ac4fde)

**Comment by aarthificial** [comment]
Can you take a look at #1026 to see if it fixes the issue completly?

**Comment by HikariIsChillin** [comment]
From my tests it fixed everything except inside of cached nodes.

If you use the same shader as before but like this it will still have the issue, the destinationUV is resized to the size of the cached node, but when you change the scale is stays at the size the node had before scaling.

```tsx
import { Node, Rect, makeScene2D } from '@motion-canvas/2d'

import destinationUVbug from '../shaders/destinationUVbug.glsl'

export default makeScene2D(function* (view) {
	// view.shaders(destinationUVbug)

	view.add(
		<Node cache>
			<Rect size={view.size().sub(200)} shaders={destinationUVbug} />
		</Node>
	)
})
```

One funny interaction I noticed is that if you set the size of the rect with numbers or by subtracting from the view.size() like in the code above, the shader destinationUV will fit the Node properly at the normal scale, but if you do:

```tsx
<Node cache>
	<Rect size={view.size().mul(0.5)} shaders={destinationUVbug} />
</Node>
```

Multiplying or dividing, the scale is broken just like when changing the scale of the scene.
My guess is both of these are the same issue.

**Comment by aarthificial** [comment]
@HikariIsChillin Thanks for checking this out!
I added a fixup to #1026 now everything should work

**Comment by HikariIsChillin** [comment]
@aarthificial Everything is working now
