### ISSUE TITLE
Example scene for Code node

### ISSUE THREAD

**Issue by mancopp** [motion-canvas/motion-canvas#1022]
**Description**
The deprecation of the CodeBlock node and introduction of the Code node necessitate updating MC example scenes. Currently lacking representation of the Code node, MC examples need a dedicated Code scene to demonstrate its functionality and usage effectively.

**Proposed solution**
Create Code Scene: Develop a new example scene showcasing the Code node's various use cases and functionalities.

**Comment by aarthificial** [comment]
Closed by #1023
