### ISSUE TITLE
Use time events for duration

### ISSUE THREAD

**Issue by aarthificial** [motion-canvas/motion-canvas#171]
**Description**
Time events allow for editing *when* something should happen, but they could also define *how long* it should last.

**Proposed solution**
From a technical perspective, this is already possible.
The following example will make the tween last as long as the `event` event:
```ts
useScene().timeEvents.register('event')
const duration = useScene().timeEvents.get('event').offset;
yield* circle().scale(2, duration);
```
But it would be nice to have a compact helper function for this:
```ts
yield* circle().scale(2, useDuration('event'));
```

**Comment by Tandashi** [comment]
**Note for others**: Working on this.
