### ISSUE TITLE
Inconsistent playhead behavior at composition end.

### ISSUE THREAD

**Issue by 20milliliter** [motion-canvas/motion-canvas#178]
**Describe the bug**
Under certain conditions the playhead is not stopped/looped at the end of the composition.
Under other conditions, it does.

**To Reproduce**
1. Disable Looping.
2. Set the render range of the composition to not reach the end completely.
3. Play the composition.
4. When encountering the end of the composition, the playhead stops.
5. Set the render range of the composition to reach the end completely.
6. Play the composition.
7. When encountering the end of the composition, the playhead does not stop.

**Expected behavior**
I can't tell.

**Package versions:**
- core: 2.0.0
- ui: 2.0.0

**Comment by aarthificial** [comment]
The expected behavior would be for the playback to stop upon reaching the end

**Comment by 20milliliter** [comment]
I would have assumed so. However, I didn't want to assume due to just getting my hands on it.
You can reproduce?

**Comment by aarthificial** [comment]
Yes, I can. The behavior when the range is smaller also seems incorrect -the playback doesn't stop. The time gets clamped so the animation pauses, but the preview is still in "playing" mode.
