### ISSUE TITLE
Text is invisible in Firefox

### ISSUE THREAD

**Issue by TomatechGames** [motion-canvas/motion-canvas#179]
**Describe the bug**
By default, Firefox has `dom.textMetrics.fontBoundingBox` disabled, meaning that Text components dont render at all (this includes the HTML embeds of Motion Canvas animations)

**To Reproduce**
In a fresh install of Firefox with default settings, try to view a scene that uses a Text component

**Expected behavior**
The text is displayed

**Additional context**
A workaround for users is to manually enable `dom.textMetrics.fontBoundingBox` within Firefox's config by typing `about:config` in the address bar

**Comment by LegoGuy32109** [comment]
Would love to have this mentioned in the docs somewhere when following quickstart or the signals paged https://motion-canvas.github.io/docs/signals

**Comment by n3oney** [comment]
I've found another text related bug that only happens on FF, so not sure if I should open a new issue or mention it here. Text wrapping doesn't work, it always renders on one line
![image](https://user-images.githubusercontent.com/30625554/217674166-4e4abda4-a2e4-4ffa-b440-01cb9578c041.png)
*chrome on the left, firefox on the right*

(no matter if it's preformatted or auto-wrapping)

**Comment by exdeejay** [comment]
@n3oney can you make a separate issue with your reply?

**Comment by n3oney** [comment]
Sure.
