### ISSUE TITLE
Code node

### ISSUE THREAD

**Issue by Arnau478** [motion-canvas/motion-canvas#181]
**Description**
Whenever you need to add some syntax-highlighted code you have to do something like this:
```
view.add(
    <Layout>
        <Text fill={...}>...</Text>
        <Text fill={...}>...</Text>
        <Text fill={...}>...</Text>
        {/* And so on, for each token... */}
    </Layout>
);
```

**Proposed solution**
A `Code` node, which takes care of all this. You pass a code snippet to it, the language is written on, and a color palette. It then automatically renders correctly, based on the syntax of that language.

**Considered alternatives**
A more concise way of formatting text, something like:
```
<Text><red>var</red> num = <green>3</green></Text>
```

**Additional context**
It may be tricky to specify the palette to use, but it's totally doable

**Comment by aarthificial** [comment]
We do have a `CodeBlock` node but for some reason it doesn't appear in the api docs:
```tsx
import {makeScene2D} from '@motion-canvas/2d/lib/scenes';
import {CodeBlock} from '@motion-canvas/2d/lib/components/CodeBlock';
import {waitFor} from '@motion-canvas/core/lib/flow';

export default makeScene2D(function* (view) {
  view.add(
    <CodeBlock language="tsx">
      {`export default makeScene2D(function* (view) {
  // your animation here        
});`}
    </CodeBlock>,
  );

  yield* waitFor(5);
});
```
I'll be releasing the source code of my newest video soon, it will include lots of examples of how to use it.

**Comment by Ross-Esmond** [comment]
Maybe because it's not exported the same as the others. If I can figure out a way to select the languages to load I will.
