### ISSUE TITLE
Typo in flow section

### ISSUE THREAD

**Issue by Spartan09** [motion-canvas/motion-canvas#182]
<img width="734" alt="image" src="https://user-images.githubusercontent.com/31277910/216779586-3c66d72b-e0f0-49d7-b2e9-9a4fc46d99f3.png">

It should be `circle` and not `circle()`.

**Comment by aarthificial** [comment]
The snippet is correct. That's how [`createRef` works](https://motion-canvas.github.io/docs/references#createref-function), invoking it retrieves the reference, in this case the circle node.
