### ISSUE TITLE
Question on introduction video code

### ISSUE THREAD

**Issue by ch3coohlink** [motion-canvas/motion-canvas#192]
Don't know is this issue appropriate but it seems I can't create a new discussion so I put it here anyway...

On video [Animating with Code - Motion Canvas](https://youtu.be/WTUafAwrunE?t=350) there are 3 pieces of code : 
```js
yield rect.value.radius(160, 0.6)
yield* rect.value.fill('#68ABDF', 0.6)
```
```js
const task = yield rect.value.radius(160, 0.6)
yield* rect.value.fill('#68ABDF', 0.6)
yield* join(task)
```
```js
yield* all(
  rect.value.radius(160, 0.6),
  rect.value.fill('#68ABDF', 0.6),
)
```

After watching this video, my understanding on motion-canvas behavior is something like this:
 - write a generator which step the animation by one frame per yield
 - yield this generator inside another generator to compose them
 - use yield* to pull out all frames in a generator

The video says that this 3 pieces are identical on function, so based on my understanding, there are few questions bothering me:
 - if the radius animation is yield for only once, then how this animation continued?
 - If I just neglect the first question, I can see that the last piece do start two animation simultaneously, but I think the first and the second one start the radius animation one frame earlier than the color animation.

Please help! Thank You!

**Comment by aarthificial** [comment]
In Motion Canvas, we call this concept threading. Unfortunately, there's no documentation on it yet.
But in short, yielding a generator (a value returned by the generator function) creates a separate thread for it. During the animation, Motion Canvas iterates over every thread and progresses it once, by calling their `next()` method. 

So doing this:
```ts
yield rect.value.radius(160, 0.6)
```
can be thought of as spawning a new thread, that will run concurrently with the main animation function.

A more in-depth explanation will come shortly in a form of a page on our documentation page.
