### ISSUE TITLE
npm init @motion-canvas doesn't work

### ISSUE THREAD

**Issue by FilledStacks** [motion-canvas/motion-canvas#196]
**Description**
When I run `npm init @motion-canvas` it prints out the following. It's confusing for developers that are not web developers and are unfamiliar with the npm system and how to use it with packages that are not on npm. 

```shell
npm ERR! code E404
npm ERR! 404 Not Found - GET https://npm.pkg.github.com/@motion-canvas%2fcreate - npm package "create" does not exist under owner "motion-canvas"
npm ERR! 404 
npm ERR! 404  '@motion-canvas/create@latest' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/danemackier/.npm/_logs/2023-02-05T13_14_09_505Z-debug-0.log
```

I think there needs to be clearer instructions on how to get started from scratch. If you give me clear instructions I'll make a PR to update the docs as well.

**Comment by FilledStacks** [comment]
After running `npm init @motion-canvas` in the github repo it's working and creating the project. 

Now when I run `npm install` in the created project I get 

```shell
npm ERR! code E404
npm ERR! 404 Not Found - GET https://npm.pkg.github.com/@motion-canvas%2f2d - npm package "2d" does not exist under owner "motion-canvas"
npm ERR! 404 
npm ERR! 404  '@motion-canvas/2d@^2.0.0' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/danemackier/.npm/_logs/2023-02-05T13_23_03_387Z-debug-0.log
```

**Comment by dtamai** [comment]
@FilledStacks, do you have some custom npm configuration that causes it to use Github's registry (_npm.pkg.github.com_) instead of npm's one (_registry.npmjs.org_)?

You can check that the package exists in the npm registry [here](https://registry.npmjs.org/@motion-canvas%2f2d).

**Comment by FilledStacks** [comment]
@dtamai I don't think so. I use to use motion canvas back when it was patreon only, that might have done something?

I'll google how to reset npm registry and then try again. Will report in a few minutes.

**Comment by 20milliliter** [comment]
Unless you plan to contribute, you do not need to download the repo.
The package exists in the npm registry and so `npm init @motion-canvas` is all you need to install it (ideally, in a newly created directory).

**Comment by FilledStacks** [comment]
@dtamai and @20milliliter thank you. 

I checked the .npmrc and saw that my old entries for motion-canvas were still there. I removed that and now it's working. 

Thanks for your time. Much appreciated .

**Comment by 20milliliter** [comment]
Still, I agree it wouldn't hurt to include a `Unless you plan to contribute, you do not need to download the repo to use Motion Canvas.` tip somewhere near the top of the quickstart page.

**Comment by MarcinOrlowski** [comment]
I'd vote to reopen  because docs are still out dated and inaccurate. In my particular case I both had to install `@motion-canvas/create` manually and then change the `init` invocation argument to make things work here:

```bash
$ npm init @motion-canvas@latest                                                                                                                                                                                                                             
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "@motion-canvas": name can only contain URL-friendly characters

$ npm install @motion-canvas/create                                                                                                                                                                                                                      
added 4 packages, and audited 5 packages in 671ms

$ npm init @motion-canvas@latest                                                                                                                                                                                                                             npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "@motion-canvas": name can only contain URL-friendly characters

$ npm init @motion-canvas                                                                                                                                                                                                                               
✔ Project name … my-animation
✔ Project path … my-animation
✔ Language › TypeScript (Recommended)

√ Scaffolding complete. You can now run:
  cd my-animation
  npm install
  npm run serve

$ node -v
v18.15.0
$ npm -v                                                                                                                                                                                                                                                                                
8.1.2
```

**Comment by aarthificial** [comment]
@MarcinOrlowski It's literally the first entry in the troubleshooting:
http://localhost:3000/docs/quickstart#troubleshooting

**Comment by RomanDietenmeier** [comment]
I'd urge to reopen too, as I got the same error and did not know of the troubleshooting hint, before I came here.
![image](https://user-images.githubusercontent.com/43014719/230782851-5705fbfd-63ff-46fd-bfc8-eb52d690ff75.png)
