### ISSUE TITLE
vite 4?

### ISSUE THREAD

**Issue by DeveeiveD** [motion-canvas/motion-canvas#197]
**Description**
How easy is it to update to vite 4?

**Proposed solution**
...

**Considered alternatives**
...

**Additional context**
...

**Comment by aarthificial** [comment]
It's hard to say but I think it's a good idea to upgrade.
Looks like `@preact/preset-vite` already supports Vite 4, which is the only vite dependency we use. So it comes down to upgrading our `vite-plugin`.

**Comment by chris-findlay** [comment]
@DeveeiveD what are the notable changes relative to the current version?

**Comment by guifeliper** [comment]
I have created a PR with the update, reading the documentation of Vite, there are updates that impact us.
