### ISSUE TITLE
Warning about running in WSL2

### ISSUE THREAD

**Issue by andreadev-it** [motion-canvas/motion-canvas#214]
**Description**
When creating a project from within WSL2, there might be problems with Vite server not being able to watch the files for changes.
As someone that never used Vite, this sturtled me for a while. In the end, I've seen [this warning in Vite docs](https://vitejs.dev/config/server-options.html#server-watch) and fixed my issue by moving my project inside a linux filesystem (a folder in my linux home directory).

I thought that, since WSL is becoming more and more common between developers, it might be useful to add a warning in the "Get started" page in the point where the hot reloading feature is explained.

Thank you a lot for this very interesting project!

**Comment by aarthificial** [comment]
I agree. It could save a lot of people some time.

> Thank you a lot for this very interesting project!

No problem!
