### ISSUE TITLE
Additional timing/easing functions

### ISSUE THREAD

**Issue by DoctorBracewell** [motion-canvas/motion-canvas#220]
**Description**
The tweening docs link to the https://easings.net/ site with a number of easing functions but only some are actually implemented in the library, I'd be very happy to pop the rest in as a first contribution if it sounds like a good idea!

**Proposed solution**
Update `core/tweening/timingFunctions.ts` to export all 10 easing functions from the site, with in/out/both versions for all of them (30 functions plus `sin`, `cos` and `linear` functions so 33 in total).

Proposed functions to include:
- Sine
- Quadratic
- Cubic
- Quartic
- Quintic
- Exponential
- Circular
- Back
- Elastic
- Bounce

Functions could potentially live in files named after their formula, e.g 
```ts
// core/tweening/timing/expo.ts

export function easeOutExpo(value: number, from = 0, to = 1) {
	...
}

export function easeInExpo(value: number, from = 0, to = 1) {
	...
}

export function easeInOutExpo(value: number, from = 0, to = 1) {
	...
}
```
and `core/tweening/index.ts` would re-export all of those functions.

However it doesn't seem like any other modules use additional folders, so maybe it would be best to just have `expo.ts`, `cubic.ts` etc. all under the `tweening/` folder or just keep all the functions in one large file like they are currently (potentially less chance of accidentally breaking the current ES module layout).

**Considered alternatives**
There might be some other collection of easing implementations available to use, but it seems the motion canvas ones use library-specific functions like `map` and `remap` so I think it would be good to implement rest of the common easing functions just for consistency.

**Comment by aarthificial** [comment]
Agree, I don't think there's a need to split them into separate files since they are more of a "write once, never edit" kind of thing, so we shouldn't worry about future maintenance. But if you want to separate them into `expo.ts` (without sub-folders), etc, then go ahead.
