### ISSUE TITLE
Pass variables from player package to project scenes

### ISSUE THREAD

**Issue by therealtimhawkins** [motion-canvas/motion-canvas#222]
**Description**
I would like to be able to pass arguments to a projects scenes via the player package such as image sources, aspect ratios or colours. 
I feel this would open up some interesting possibilities for the package such as dynamically changing images, colours or text.

**Proposed solution**
Perhaps adding an attribute to the player package component to provide a single props object:

```
<motion-canvas-player
      src="/@id/__x00__virtual:template"
      style="aspect-ratio: 16 / 9"
      data-props="{ imageSource: "https://mycdn.com/image", colours: ['red', 'blue'] }"
></motion-canvas-player>
```

This would then be available to each scene in the project:

```
export default makeScene2D(function* (view, props) {
      const image = createRef<Image>()
      view.add(
        <Image
          ref={image}
          src={props.imageSource}
          width={200}
          height={200}
        />
      )
});
```

Sorry this is light on actual implementation details, really happy to be guided around the best solution here.

**Considered alternatives**

**Additional context**
Thanks again for this project, it's great work!

**Comment by therealtimhawkins** [comment]
Thanks Jacob. Yep, makes sense. I'll take a look around the code base today and get back to you if ive got any issues 👍

**Comment by therealtimhawkins** [comment]
```

**Comment by therealtimhawkins** [comment]
```

**Comment by aarthificial** [comment]
I haven't thought about this. Making the variables project-scoped seems like a much better idea.
