### ISSUE TITLE
Please add triangles

### ISSUE THREAD

**Issue by Xyndra** [motion-canvas/motion-canvas#225]
**Description**
Triangles are a very important shape in mathematics and should definitely be added.

**Considered alternatives**
It would also be quite good for there to be a "Polygon" object that simply creates a shape with an array of points independent of the number of points inside the array.

**Comment by gabriel-peracio** [comment]
As a workaround, you can make your own polygons (including triangles) with

```jsx
<Line
  fill={"#0F0"}
  lineWidth={5}
  stroke={"#F00"}
  points={[
    [0, 0],
    [100, 100],
    [-100, 100],
    [0, 0],
  ]}
/>;
```

Result:
![image](https://user-images.githubusercontent.com/8999086/217275857-c4f80ba0-53cc-4b6a-b4a2-49c0c0fe0839.png)


I'm not sure that `closed={true}` is needed, didn't seem to do anything, so I left it out.

Some prebuilt or configurable shapes would be nice (triangles, n-sided polygons, n-pointed stars, trapezoids, parallelograms, chevrons, etc) but you can make your own component to build those

**Comment by Ross-Esmond** [comment]
`closed={true}` should draw a line from the end to the start, such that you don't need to match the start and end points, so it would be:
```ts
<Line
  fill={"#0F0"}
  lineWidth={5}
  stroke={"#F00"}
  closed={true}
  points={[
    [0, 0],
    [100, 100],
    [-100, 100],
  ]}
/>;
```

**Comment by Xyndra** [comment]
thanks
