### ISSUE TITLE
Can't render size animations if a child contains an image with a src from a URL

### ISSUE THREAD

**Issue by Reinachan** [motion-canvas/motion-canvas#234]
**Describe the bug**
When attempting to render an animation of the width of a parent that has an image child element with the src property set to a url, the renderer will crash with the error below. It will work correctly inside the preview, but will error when rendering.

**To Reproduce**
Below is a more or less minimal example that will cause the error

```ts
const USERNAME = 'Reina';
const PICTURE = 'https://media.kitsu.io/users/avatars/171606/large.jpeg';

const fontFamily = 'sans-serif';
const BACKGROUND = '#312631';

export default makeScene2D(function* (view) {
	const background = createRef<Layout>();

	view.add(
		<Layout layout justifyContent='end' margin={[0, 80, 80, 0]}>
			<Layout clip width='0%' ref={background}>
				<Rect
					height={122}
					width='100%'
					padding={[11, 25, 11, 20]}
					fill={BACKGROUND}
					layout
					gap={25}
					radius={{
						top: 5,
						left: 5,
						bottom: 0,
						right: 0,
					}}>

					{/* This clip property seem to be the culprit */}
					<Circle width={100} height={100} fill='#000' clip>
						<Image src={PICTURE} width={100} height={100} />
					</Circle>

					<Text
						fill='#ffffff'
						fontFamily={fontFamily}
						fontSize={40}
						fontWeight={700}
						lineHeight={48}
						margin={0}
						padding={0}>
						{USERNAME}
					</Text>
				</Rect>
			</Layout>
		</Layout>
	);

	// Problematic animation
	yield* tween(0.4, (value) => {
		background().size.x(`${easeInOutCubic(value, 0, 100)}%`);
	});
	yield* tween(0.4, (value) => {
		background().size.x(`${easeInOutCubic(value, 100, 0)}%`);
	});
});
```

**Expected behavior**
This should render like it does in the preview window

**Console errors**
![image](https://user-images.githubusercontent.com/16106839/217268163-c18b90bd-96b2-4dbd-99b6-a2b7ea245efb.png)

**Package versions (please complete the following information):**

- core: 2.0.0
- ui: 2.0.0

**Comment by Reinachan** [comment]
Correction, it's the image that is causing the issue, not the clipping

**Comment by Reinachan** [comment]
Correction again, when I downloaded the image and imported it locally, there was no issue, so it seems this only happens if you have a url as the src

**Comment by aarthificial** [comment]
Looks like it's caused by the CORS configuration of the server that hosts the image:
https://stackoverflow.com/questions/25753754/canvas-todataurl-security-error-the-operation-is-insecure
I'm not sure if there's anything we can do about it.
