### ISSUE TITLE
Option to _disable_ Anti-Aliasing

### ISSUE THREAD

**Issue by Wunkolo** [motion-canvas/motion-canvas#235]
**Description**
I like to make short "explainer gifs" when making a big write-up and have great interest in motion-canvas.
I come from utilizing Adobe After Effects to make gifs such as this:
![AVX2](https://raw.githubusercontent.com/Wunkolo/qreverse/master/images/AVX2.gif)
![SAD](https://raw.githubusercontent.com/Wunkolo/qAverageColor/master/media/SAD.gif)

The problem and biggest challenge I had with making these gifs though is that their file-size is very correlated by the characteristics of the motion and the amount of colors that are to be animated. One way that helps, in my experience, is to _disable_ anti-aliasing to reduce the amount of colors in exchange for "quality". This also helps when exporting a gif with transparency and there is no support for partial-transparency. This might also aid in viewport performance.

**Proposed solution**
An option to _disable_ anti-aliasing for the viewport and for rendering to turn off Anti-Aliasing on shapes, lines, text, and images.

**Additional context**
For SVGs, I believe the [shape-rendering](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/shape-rendering) option may be utilized which accomplishes what I am looking for:
![image](https://user-images.githubusercontent.com/644247/217330378-ad9d371a-08fa-4c0a-8d57-48ee011d8c0f.png)
Though, ideally this is a systematic option and not something that has to be configured per-shape.

For images, there is [CanvasRenderingContext2D.imageSmoothingEnabled](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled) which would maintain aliasing on images.
![image](https://user-images.githubusercontent.com/644247/217332161-f8693805-e87f-453e-8f38-00a342e2b839.png)

There is also [CanvasRenderingContext2D.textRendering](https://devdocs.io/dom/canvasrenderingcontext2d/textrendering)

The feature, as displayed in After Effects
![AfterFX_lfTZ0Q2C33](https://user-images.githubusercontent.com/644247/217327872-7fd2b658-a1dd-4be7-81c5-172ba40473d8.gif)

**Comment by aarthificial** [comment]
Images already have the [`smoothing`](https://motion-canvas.github.io/api/2d/components/Image#smoothing) property which controls the drawing. which controls the value of [CanvasRenderingContext2D.imageSmoothingEnabled](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled).
I don't think there's a way to disable antialiasing for shapes, though. We don't use SVGs, we use the [CanvasRenderingContext2D](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D) to do the drawing.
