### ISSUE TITLE
Change Code theme colours

### ISSUE THREAD

**Issue by bashcole** [motion-canvas/motion-canvas#236]
**Description**
I can't seem to find a way to change the code styling.

I like to use Monokai Pro and it will be pretty good to be able to implemented.

**Comment by Ross-Esmond** [comment]
I wrote `code-fns`. I'll be adding code styling soon. At first I'll probably just add more ready made options, like Monokai.

**Comment by Ross-Esmond** [comment]
@aarthificial This can be closed.

**Comment by aarthificial** [comment]
Closed by #279
