### ISSUE TITLE
Automatically set lineHeight from fontSize

### ISSUE THREAD

**Issue by exdeejay** [motion-canvas/motion-canvas#238]
**Description**
The `lineHeight` property on Text components defaults to a small size that does not fully contain larger sized text. This results in the bounding box for the component cutting off the top and bottom of the text, which can lead to clipping issues when tweening opacity.

**Proposed solution**
Set `lineHeight` automatically when not otherwise specified so that it is tall enough to fully contain the text in the component.

**Additional context**
![Screenshot from 2023-02-07 17-12-21](https://user-images.githubusercontent.com/13634296/217378642-02f3ff3f-4990-4be3-8a3a-6a2f1cbeee37.png)

```ts
let text = createRef<Text>();
view.add(<Text ref={text} text={'Hello world'} fill="white" fontSize={200} opacity={0} />)
yield* text().opacity(1, 1);
yield* waitFor(1);
```

**Comment by brandonpelfrey** [comment]
I'm happy to work on this issue.

**Comment by aarthificial** [comment]
Alright, to stay consistent I'd recommend using the `Length` type (like `width` and `height`) and making percentage values based on the font size.
