### ISSUE TITLE
Attempting to lerp without an initial value results in an opaque error message

### ISSUE THREAD

**Issue by hhenrichsen** [motion-canvas/motion-canvas#243]
**Description**
Trying to lerp a value without an initial value results in an error message like:
```
Cannot use 'in' operator to search for 'lerp' in null
```

**Proposed solution**
The error message should instead check for a from value and throw a clearer error when trying to lerp a value that does not yet exist.

**Comment by exdeejay** [comment]
Can you provide a short example that triggers this error?

**Comment by exdeejay** [comment]
Never mind, found it from another bug. This appears to be coming from the function `deepLerp()`:
```ts
export function deepLerp(from: any, to: any, value: number): any {
  if (value === 0) return from;
  if (value === 1) return to;

  if (typeof from === 'undefined' || typeof to === 'undefined') {
    return undefined;
  }
  ...
  if ('lerp' in from) {
    return from.lerp(to, value);
  }
  ...
```

My first thought is to copy the `undefined` check and simply return `null` if either `from` or `to` is `null`, but that would turn this error into a silent fail. Perhaps it would be better to change both `undefined` and `null` cases to throw an error instead?

**Comment by hhenrichsen** [comment]
Yeah, I think a throw is better here so that we aren't silently failing to do something. I could see another bug being filed if we silently fail and didn't lerp along the lines of "why is my rectangle's color just appearing instead of fading in".

Alternatively it might make sense to give more things default values, but those are not mutually exclusive.
