### ISSUE TITLE
CodeBlock component not in documentation

### ISSUE THREAD

**Issue by ribru17** [motion-canvas/motion-canvas#244]
**Description**
As it stands there is no mention of the `CodeBlock` component in the online documentation and I have mainly had to navigate the source code to find out how to use the `CodeBlock` feature. It would be great if this was documented on the website. Thanks!

**Comment by zachtl** [comment]
Interested in contributing. Where abouts could I find source code so I can look into it myself. Totally not asking because I was trying to find if there was a codeblock element within MC

**Comment by Ross-Esmond** [comment]
I can write a draft later today.
