### ISSUE TITLE
Ability to Search in API/Docs

### ISSUE THREAD

**Issue by xCloudK** [motion-canvas/motion-canvas#250]
An easy way to locate features. If a user doesn't know how to find something, they can just use the search feature. I'm not aware on how the website works or any frontend/backend knowledge so I can't propose a solution. Thanks

**Comment by ksassnowski** [comment]
Agrred. I think signing up for [Algolia's  docsearch](https://docsearch.algolia.com/) would go a long way. I'm using it on all my documentation pages, too.

**Comment by ksassnowski** [comment]
I think we can close this now that it’s implemented and works beautifully 🤫

**Comment by ksassnowski** [comment]
#335 for reference. 

Oh, and #336
