### ISSUE TITLE
Is it possible to use SVG or import my own SVG into videos ?

### ISSUE THREAD

**Issue by sorasful** [motion-canvas/motion-canvas#272]
Hi there,

I was wondering if it is possible to add a SVG into a video just like a regular shape (like Circle or Rect). 

If so, how ? I've seen that there are multiple SVG ready like "PlayArrow", but I feel like they are meant to be used in the interface more than in the videos, am I right ?

Thanks for your time !

**Comment by hhenrichsen** [comment]
You can import these as an `Image`; assuming your svg is in the `public` folder and named `mySvg`:
```ts
import mySvg from "../../public/mySvg.svg";

export default makeScene2D(function* (view) {
    view.add(
        <Image src={mySvg} size={[100, 100]}></Image>
    )
});
```

**Comment by Tandashi** [comment]
Also for Reference: #237
Documentation regarding this is already in the works.

**Comment by sorasful** [comment]
Thank you very much.
