### ISSUE TITLE
Text never wrapping on Firefox.

### ISSUE THREAD

**Issue by n3oney** [motion-canvas/motion-canvas#284]
**Describe the bug**
Text just does not wrap. It always renders in one line, no matter if you use preformatted text or try wrapping it automatically.
(Chrome on the left, Firefox on the right)
![image](https://user-images.githubusercontent.com/30625554/217935820-f31a5472-89a8-405a-801e-573f0348e0f6.png)

**To Reproduce**
```ts
function* problem(scene: View2D) {
  scene.add(
    <Text
      fill="white"
      fontFamily="monospace"
      textWrap="pre"
      text={`hello {
  world
}`}
    />
  );
}
```

**Expected behavior**
The text should wrap.

**Package versions:**
- core: [e.g. 2.2.0]
- ui: [e.g. 2.2.0]

**Additional context**
This only happens on Firefox.

**Comment by exdeejay** [comment]
Appears to be caused by `Intl.Segmenter` not being supported on Firefox. I'll claim this one.
