### ISSUE TITLE
Feature request: scrubbing when dragging in the timeline with seeking starting with onMouseDown instead of onMouseUp

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [motion-canvas/motion-canvas#286]
**Description**
Feature request: seeking in the timeline on onMouseDown instead of onMouseUp.

Right now nothing happens when you click and drag in the timeline until you let go of the click and you seek to that position. Enabling seeking on onMouseDown would fix this and make it easier to preview what is happening and make the UI more responsive as well.

Hopefully this wouldn't break seeking in some way.

**Proposed solution**
Either add a setting for seeking to use onMouseDown instead of onMouseUp or just replace onMouseUp with onMouseDown for seeking.

There is a nice bar looking thing following the mouse cursor so it should be possible to reuse that logic to seek whenever the mouse cursor is over a new whole frame.

**Considered alternatives**
Seeking with onMouseUp which works but is not great.

**Additional context**

**Comment by aarthificial** [comment]
This issue sounds like you want to change when the seeking happens. But I'm confused by this part:
>  reuse that logic to seek whenever the mouse cursor is over a new whole frame.

This sound more like full-on scrubbing the timeline. As in dragging your mouse and having the playhead smoothly follow.
Could you clarify that?

**Comment by henrikvilhelmberglund** [comment]
Yes, my bad, it should be scrubbing, but seeking starting on mousedown is a prerequisite for that.

Kind of like this (from Blender)
![blenderscrubbing](https://user-images.githubusercontent.com/110549389/218153699-2d4bb5b3-a85e-44f2-b3cd-edb3c4b8e21b.gif)

**Comment by aarthificial** [comment]
We can add that but keep in mind that the time it takes to seek backward is linearly proportional to the duration of the scene.
Here's an example from the Deferred Lightning video:
![image](https://user-images.githubusercontent.com/64662184/218167600-bc550a62-9b73-4571-8b01-16ff6b368029.png)
80ms seeking time would result in around 10 frames per second so scrubbing will often feel laggy.

**Comment by GufNZ** [comment]
Would a deferred render work?  E.g. if while scrubbing, you stop for long enough to debounce, we seek&render then, so a quick drag is the same as before but a drag&hold shows the playback at that time, allowing the user to decide if this is where they want to let go or not..?
