### ISSUE TITLE
Docs: Add an updating guide

### ISSUE THREAD

**Issue by hhenrichsen** [motion-canvas/motion-canvas#288]
**Description**
We probably want a page that describes an update process, as well as any migration steps for breaking changes when they happen.

**Comment by aarthificial** [comment]
Yes, we used to have a migration section during early access: https://github.com/motion-canvas/motion-canvas/commit/804a082911b2af0a0c35a97b7976fd0660f7e052
We'll add it back when there are breaking changes to put there.

I agree with the need for an "update guide" (ideally with a troubleshooting section)

**Comment by Tandashi** [comment]
If currently no one is working on this., would love to tackle this and get that on the way.
