### ISSUE TITLE
Viewport Information in the UI

### ISSUE THREAD

**Issue by hhenrichsen** [motion-canvas/motion-canvas#289]
**Description**
It'd be nice to display a couple pieces of info in the editor UI:
- [x] The current viewport center, and buttons to return it to default as well as copy the current value as a Vector2 (and their associated hotkeys)
- [x] The current mouse hover location (if it's over the viewport), and a button that displays the hotkey to copy that as a Vector2
- [x] The current zoom level, and buttons to zoom in / out / reset zoom (and their associated hotkeys) 
  #531
  #444
- [x] The current version of Motion Canvas 
  #501

**Proposed solution**
Perhaps these would be good to include in a bar at the top of the viewport?

**Comment by aarthificial** [comment]
I think we could put it on a status bar.
As mentioned in https://github.com/motion-canvas/motion-canvas/issues/19#issuecomment-1419484450

I'm claiming this issue for myself, though. 
I'd like to keep absolute control over the UI until we have a proper design system/guide.

**Comment by nrthbound** [comment]
Would definitely like to see, at the very least, the current zoom level so I know when I'm at 50%, 100%, or 150%. That would be quite handy for me in terms of knowing what my render could potentially look like.

**Comment by Logon27** [comment]
> I think we could put it on a status bar. As mentioned in [#19 (comment)](https://github.com/motion-canvas/motion-canvas/issues/19#issuecomment-1419484450)
> 
> I'm claiming this issue for myself, though. I'd like to keep absolute control over the UI until we have a proper design system/guide.

@aarthificial It was discussed on discord that UI contributions are possible now. I would like to try taking on this feature if that is alright with you.

**Comment by aarthificial** [comment]
Closed by #737
