### ISSUE TITLE
Make building API Reference locally less confusing

### ISSUE THREAD

**Issue by Tandashi** [motion-canvas/motion-canvas#294]
**Description**
It would be nice if one doesn't need to manually remove the `generated` folder in order for the `api.json` (and other things).
Having to do it manually / not knowing about this can easily cause confusion why things are not showing up in the documentation when building locally.

**Proposal**
Add a remove for the `generated` directory in the `package.json` build script.

---

(Would love to claim this if this should get accepted)

**Comment by aarthificial** [comment]
It may be possible to detect if we're in build mode directly from our plugin: https://github.com/facebook/docusaurus/discussions/7621

**Comment by Tandashi** [comment]
Having it directly in the plugin seems like the better option. Will do it that way if possible.
