### ISSUE TITLE
Change selection of new code by default.

### ISSUE THREAD

**Issue by Ross-Esmond** [motion-canvas/motion-canvas#300]
**Description**
I think the automatic selection of new code is confusing. In this case, my expectation is that animation will not involve some automated selection, and I think the defaults should take the path of least assumption.

**Proposed solution**
Change the default parameter for `changeSelection` on `edit` from true to false.

**Comment by aarthificial** [comment]
I think confusion is something difficult to measure - your expectations may be different than mine. This is an edit animation so it feels natural to me that the newly inserted code would get highlighted.
In my opinion, though, defaults should take the path of most usability. Throughout my entire release video, I didn't need to disable the automatic selection at all. That's what I based the default value on.

**Comment by aarthificial** [comment]
Having slept on it, maybe we could make this a property of the node itself? So that you can configure it once then every edit animation afterward would either select or not select the code.

**Comment by Ross-Esmond** [comment]
Works for me. MC can have a separate property for the default, and the default default can stay the same way it is now.

**Comment by aarthificial** [comment]
Closing this in favor of #688
I added "Automatic selection" section there to define this behavior.
