### ISSUE TITLE
`textAlign` property for Layout/Text

### ISSUE THREAD

**Issue by exdeejay** [motion-canvas/motion-canvas#303]
**Description**
When using layouts, I'd like to center- or right-align text within their allotted spaces.

**Proposed solution**
A `textAlign` property that sets the CSS property of the same name.

**Considered alternatives**
The below right-aligns the text within, but it's verbose.
```tsx
<Rect layout justifyContent={'end'}>
  <Text text={"Buffer"} {...style} fontWeight={700} fontSize={72} />
</Rect>
```

**Comment by exdeejay** [comment]
I'm gonna claim this one and delay it until #259 is pushed through, since the `textAlign` property should be able to inherit its value from a parent layout.

**Comment by rafalfigura** [comment]
Anyone who is looking for the textAlign support may use this hack:

Firstly, split the string into multiple lines that will fill the available space using something like regex
```
 const lines = longString.match(/.{1,30}(\s|$)/g);
```
Then display each line inside Layout which has `alignItems={'center'}` and `direction={'column'}` prop
```
<Layout ref={question} direction={'column'} alignItems={'center'} layout>
  {
    lines.map((line, index) => {
      return <Text
        text={line}
        fontSize={70}
        ...
       />
    })
  }
</Layout>
```

**Comment by mohsinhijazee** [comment]
Would be nice to have a direction property as well which can be set as LTR (default) or RTL.

**Comment by aarthificial** [comment]
Stealing this since it's been two weeks
