### ISSUE TITLE
feat(2d): Add Icon Component

### ISSUE THREAD

**Issue by WaldemarLehner** [motion-canvas/motion-canvas#305]
**Description**

This feature will add the `<Icon />` component. It acts as a wrapper around the `<Image/>` and provides a simple API
for including SVG Icons in Motion Canvas.

**Proposed solution**

An `<Icon/>` component that makes use of the iconify API to request SVG Icons.
One can declare an Icon by using one of the 150k+ identifiers. One can also set the color of the icon using a Prop.
```tsx
view.add(
  <Layout layout>
    <Icon icon={"mdi:abjad-arabic"} size={200} color="red" />
    <Icon icon={"mdi:typewriter"} size={200} color="#bada55" />
    <Icon icon={"mdi:abugida-thai"} size={200} color="#bada55aa" />
    <Icon icon={"mdi:access-point"} size={200} color="green" />
    <Icon icon={"mdi:access-point"} size={200} color="blue" />
  </Layout>
)
```
A list of all Icons that would be accessible using this approach can be found on [Icônes](https://icones.js.org/).

The component converts the icon identifier (eg `mdi:access-point` and the provided color (eg `red`) into a URL that would look like this: `https://api.iconify.design/mdi/access-point.svg?color=red`

The Icon would be implemented as a subclass of Image. Image simply consumes the generated URL as a `src` of the image.

**Considered alternatives**
no alternatives have been considered.

**Additional context**
This feature has been discussed on Discord in the following Forum Topic: https://discord.com/channels/1071029581009657896/1073653313335218177

**Comment by ksassnowski** [comment]
While I think the idea is cool (and the implementation in the PR looks good, too), I'm not sure how I feel about tying Motion Canvas to this specific website's API. It seems like an uncharacteristic decision for such a generic tool to make. 

I do think that it's useful and the work shouldn't go to waste, but maybe this would work better as a community package? Just my 2 cents, however. This is ultimately @aarthificial call.

**Comment by aarthificial** [comment]
@ksassnowski I was thinking the same thing. 
It's a bit of a shame that the implementation started without any consultation. 

Having a community package is a great idea, as it would allow you to quickly put out opinionated things like this and share them with the rest. People are already making and sharing all sorts of crazy things. This repo, meanwhile, could act more carefully and focus on the core functionality.

**Comment by WaldemarLehner** [comment]
> to this specific website's API. It seems like an uncharacteristic decision to make for such a generic tool.

My main motivation behind using this API is that it provides loads of Icons from many different collections with a very easy-to-use API.  Other APIs tend to provide just their set of Icons. With Iconify you can get icons from Bootstrap, Google Matrial, and FontAwesome — to name a few.

Additionally, it is rather easy for the user to get the Icon identifiers.
Say, I would like to get an "alert" icon. I can head to `https://icones.js.org/collection/all?s=alert`, chose one of the 619 results, click on it, and copy-paste the identifier (
![image](https://user-images.githubusercontent.com/27686785/218257017-365b87e3-b3fb-4bae-8999-92891b228dc2.png)
) into the `icon` Signal.

If there is an API or approach that you feel could be better suited, I am open to suggestions :) 


>  It's a bit of a shame that the implementation started without any consultation.

Yeah… I was a bit too eager on that part :) 

> Having a community package is a great idea, as it would allow you to quickly put out opinionated things like this and share them with the rest. People are already making and sharing all sorts of crazy things. This repo, meanwhile, could act more carefully and focus on the core functionality.

Up to you to decide. I will do the requested changes in the PR. If you think it should be a community package, I can create a separate module from the code made in the PR.

**Comment by hhenrichsen** [comment]
My stance is that this one of the best APIs that we could pick from -- it's an aggregate of a bunch of open-source icon APIs. I'm interested in what alternatives we'd consider. Using a separate API means that we don't need maintenance or to have a process for requests for specific icons, and using an aggregate API means that we're not just tied to one set of icons.

**Comment by cyberalien** [comment]
Author of Iconify here. A bit late to the party, but I've discovered this amazing project only this week, when attempting to create video tutorials for Iconify 👋

To address few concerns:
- Yes, available icon sets list is opinionated. It includes only open source icon sets with valid open source licenses.
- Using third party API in this case could be acceptable. API is open source, icon data is open source. If things do go wrong, anyone can host their own instance of API.

All data for those icons is available at GitHub and NPM, so it is possible to generate those SVGs in Node without API. Not sure how it can be implemented though in Icon component, since it requires getting data from Node.js in component, so probably link to API is the best way to go.
