### ISSUE TITLE
Text not showing in Firefox

### ISSUE THREAD

**Issue by AtHeartEngineer** [motion-canvas/motion-canvas#309]
**Describe the bug**
Text isn't showing on firefox

**To Reproduce**
```ts
import { makeScene2D } from '@motion-canvas/2d/lib/scenes';
import {Circle, Text, Rect} from '@motion-canvas/2d/lib/components';
import {createRef} from '@motion-canvas/core/lib/utils';
import {all} from '@motion-canvas/core/lib/flow';
import { easeOutCubic, linear } from '@motion-canvas/core/lib/tweening';


export default makeScene2D(function* (view) {
  const circle = createRef<Circle>();
  const text = createRef<Text>();
  const hand = createRef<Rect>();

  view.add(
    <>
      <Text
        ref={text}
        fontSize={120}
        lineHeight={120}
        fill={'rgba(255, 255, 255, 0.6)'}
        x={0}
        y={-350}
        text={"Clock"}
      />
    <Circle
      ref={circle}
      x={0}
      width={400}
      height={400}
        fill="#e13238"
      />
      <Rect
        ref={hand}
        x={0}
        y={-100}
        width={10}
        height={190}
        fill="#009fff"
      />
    </>
  );

  yield* all(
    circle().fill('#e6a700', 1).to('#e13238', 1),
    hand().rotation(0,0).to(360, 1, linear),
  );
});

```
Using this code, the "Clock" text does not show up in the editor on firefox but shows up fine on chrome.

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/1675654/218221444-bd1fba73-a7ed-4ea7-a260-2f7fa29dd8ba.png">

**Expected behavior**
Text should show up

**Console errors**
None

**Package versions (please complete the following information):**

- core: [2.1.0]
- UI: [2.1.0]

**Comment by AtHeartEngineer** [comment]
Also, thank you, this is awesome

**Comment by hhenrichsen** [comment]
Can you double check that you're running the latest version, `2.2.0`? To do this you can do `npm update @motion-canvas/2d @motion-canvas/core @motion-canvas/ui @motion-canvas/vite-plugin --save` and then reload your editor.

**Comment by Tandashi** [comment]
Just for referencing purposes: #179

**Comment by AtHeartEngineer** [comment]
@hhenrichsen Hey! That worked. Sorry I shouldn't assumed I was up to date, I created this project yesterday, but I know it is super fresh still, so I definitely should have tried updating first. Thank you, appreciate it!
