### ISSUE TITLE
Playing audio not from the beginning not working in Chrome

### ISSUE THREAD

**Issue by pklaschka** [motion-canvas/motion-canvas#311]
**Describe the bug**
In Chrome (this doesn't happen in Firefox), tested on WIndows 11, when an audio track gets added to a project / scene, playing the scene only works from the beginning. When trying to play the scene from somewhere in the middle (e.g., frame 23), it goes into a "playing" state, but shows 0 FPS and the audio doesn't play. When switching windows (outside of Chrome), the audio starts to play. When switching back, it stops again.

Since this is pretty difficult to get across in text, here's a video where I show the bug "in action": https://www.loom.com/share/6e1219091b30488ea75e346697800bbc (sorry for the bad audio, I apperently forgot to set the correct microphone 😅 )

I was able to reproduce this with various audio files of different formats.

**To Reproduce**
Not sure, it seems to be any project with an audio file inside Google Chrome / Chromium (doesn't happen in Firefox), even with the simplest of scenes:

```ts
export default function* problem(scene: Scene) {
  yield* waitFor(60);
}
```

Then, as in the video, playing only works from the beginning, trying to play from a different frame results in `0 FPS` and nothing happening (but the audio plays when the window gets minimized).

**Expected behavior**
The animation should play (as it does in Firefox).

**Console errors**
none

**Package versions (please complete the following information):**

- core: 2.2.0
- ui: 2.2.0

**Additional context**
I feel like this is probably a weird case that happens in Chrome on Windows 11, so I can understand if this is almost impossible to reproduce. However, it's consistent on my system and I would appreciate any ideas 🙂 .

And thanks for this awesome tool, I've waited a long time for something like this to get released and it's awesome (currently using it with Firefox to avoid the bug) 🎉 !

**Comment by pklaschka** [comment]
There are some rare instances when everything works as expected, but there doesn't seem to be any pattern to it and it only works ~ 5-10 % of the time.

**Comment by aarthificial** [comment]
Hi! Can you try disabling `bufferedAssets` in your `vite.config.ts` and see if the problem still occurs?
```ts
export default defineConfig({
  plugins: [motionCanvas({
    bufferedAssets: false
  })],
});
```

**Comment by pklaschka** [comment]
@aarthificial Thanks for the quick response!

> Hi! Can you try disabling `bufferedAssets` in your `vite.config.ts` and see if the problem still occurs?
> 
> ```ts
> export default defineConfig({
>   plugins: [motionCanvas({
>     bufferedAssets: false
>   })],
> });
> ```

Interesting, that fixes the problem 🤔 . I find it interesting that this only happens in Chrome, though (as from my understanding, this has a lot more to do with the server side of things than the browser side, based on a quick glance at the Vite plugin?), but ... it is what it is.

**Comment by aarthificial** [comment]
No problem! This is a really specific problem, I also run Chrome on Windows 11 and it works for me. It may even be dependent on the hardware as far as I'm concerned. I need to check if `bufferedAssets` is even necessary anymore, to be honest.

**Comment by pklaschka** [comment]
Alright! Thanks so much for your help. I'll leave it at your discretion whether you want to close this issue or keep it open (not sure if there's anything actionable in this issue), I have my answer for now (if you want me to do additional testing at some point, please feel free to ping me, I'm happy to help in any way I can, but given the "edge-caseyness" of this, I don't know if this is worth it given that there is a solution now documented here).

Thanks again and have a nice weekend 😊 !

**Comment by JohnCido** [comment]
This exact issue happens to me too. And disabling the `bufferedAssets` do help.
To make it clear, disable this option will disable audio HMR right? So, if I changed the audio file, do I need to start the `serve` task or just refresh the web page will do the trick?

Also, I noticed that enabling this option will prevent the play head from going beyond the end of the audio track. And the exported video file will be shorter than expected because of the audio track limit. Not sure about the cause.

**Comment by aarthificial** [comment]
@JohnCido Just refreshing the page should work and I believe Vite will automatically refresh it for you.
To be honest, I haven't tested HMR for audio ever since we switched from Webpack to Vite, so it's possible it just doesn't work at all no matter the options. I'll take a look at it.

**Comment by aarthificial** [comment]
After #793 `bufferAssets` is no longer used by default. HMR for audio should also work correctly.
