### ISSUE TITLE
I see dark screen even though scene should not be empty 

### ISSUE THREAD

**Issue by SkalskiP** [motion-canvas/motion-canvas#316]
**Describe the bug**

I'm honestly confused if this is the bug or if I don't know what to do here - this is my first time using Motion Canvas.

I think I accidentally zoomed in / out too much and I can't reverse that. This is what I see:

![Screenshot 2023-02-11 at 18 42 37](https://user-images.githubusercontent.com/26109316/218272876-79962592-c336-403c-bfdb-4d3d4fd425dd.png)

This is my scene:

```ts
import {makeScene2D} from '@motion-canvas/2d/lib/scenes';
import {Circle} from '@motion-canvas/2d/lib/components';
import {createRef} from '@motion-canvas/core/lib/utils';
import {all} from '@motion-canvas/core/lib/flow';

export default makeScene2D(function* (view) {
  const myCircle = createRef<Circle>();

  view.add(
    <Circle
      ref={myCircle}
      x={-300}
      width={240}
      height={240}
      fill="#e13238"
    />,
  );

  yield* all(
    myCircle().position.x(300, 1).to(-300, 1),
    myCircle().fill('#e6a700', 1).to('#e13238', 1),
  );
});
```

I tied to kill the app and serve it again. No luck. No errors in the console.

Is there any way to center the editor back on the scene?

**Comment by aarthificial** [comment]
Hi! You can press `0` to reset the zoom

**Comment by SkalskiP** [comment]
Hi, @aarthificial 👋🏻! It worked. Thanks a lot for the help. And I'm really sorry to ask such a stupid question. It is all new to me :)

**Comment by aarthificial** [comment]
No worries! I'm glad it helped
