### ISSUE TITLE
Doc: Reloading API Reference with unchecked "Inherited members" produces bad TOC

### ISSUE THREAD

**Issue by WaldemarLehner** [motion-canvas/motion-canvas#319]
**Describe the bug**
Reloading any of the autogenerated API Reference Pages that have inherited members while having *Inherited members* unchecked in the filters results in wrong Properties on the TOC on the right.

**To Reproduce**

1. Go to any API Reference that inherits Properties / Methods, e.g. https://motion-canvas.github.io/api/2d/components/Rect/
2. By default, inherited Properties / Methods are shown: 
![image](https://user-images.githubusercontent.com/27686785/218284414-1505c173-f589-436c-a5be-c05334436836.png)
3. Uncheck Inherited Members on the Filters: 
![image](https://user-images.githubusercontent.com/27686785/218284435-953905cd-bc8c-4012-b86b-9dea1830e980.png)
4. Properties show up correctly on the right
5. Reloading the page results in a bad TOC: ![image](https://user-images.githubusercontent.com/27686785/218284463-71544176-b757-42b6-9f67-db3db2c37f5c.png)
6. Checking and unchecking Inherited Members does *not* fix the issue.

**Expected behavior**
After Reloading the page the TOC should remain as in Point 3

**Console errors**
no output

**Package versions (please complete the following information):**

v2.3.0

**Additional context**
Browsers used:
Mozilla Firefox 109.0.1 (64-bit), Manjaro Linux
Chromium 109.0.5414.119 (Official Build) Arch Linux (64-bit)

**Comment by aarthificial** [comment]
This most like has to do with the server-side rendering HTML not being properly updated after reading the filter settings from local storage.

**Comment by WaldemarLehner** [comment]
Soo.. I started the docs locally via `npm run docs:start` and could not replicate.

Serving the generated Build with `npm run docs:build` and `npx serve pages/docs/build` , I **managed to replicate the issue** locally. 

This is - however  -  using version `2.2.0`, not the one defined in the docs' `package.json` (`^2.2.0`), reason being that the newer version [break for me (see Discord Forum Thread)](https://discord.com/channels/1071029581009657896/1073730420979531797/1073730420979531797)

**Comment by aarthificial** [comment]
Yeah, as I said, this is a problem with server-side rendering which is not used during development. I encountered a similar issue when implementing the Discord and GitHub counters, where a class would not get removed in the HTML, even though it should, according to the application state. As if the app assumed that the server returned the HTML without the class already.

I can confirm that anything above `2.2.0` will break cause we're using some internal features of Docusaurus for our API plugin. But that's a separate issue.

**Comment by WaldemarLehner** [comment]
> This most like has to do with the server-side rendering HTML not being properly updated after reading the filter settings from local storage.

Spot on.
Switching to a page when the App is "hydrated" does not result in that bug

**Comment by WaldemarLehner** [comment]
I added a console.log to `ApiItem.tsx` to check the `toc` variable which contains the TOC data with filters applied.  On hydration it does have the correct value and gets passed to `<DocProvider/>`. So it seems that DocProvider fails to update the value properly. I cannot look into DocProvider as it complains about missing type definitions :(
![image](https://user-images.githubusercontent.com/27686785/218469505-7ed3c8ee-affa-4cba-a6c5-1ff2ab59a6d7.png)

The file in question is here: https://github.com/motion-canvas/motion-canvas/blob/main/packages/docs/src/components/Api/ApiItem.tsx#L74

**Comment by aarthificial** [comment]
`DocProvider` would be here:
https://github.com/facebook/docusaurus/blob/a308fb7c81832cca354192fe2984f52749441249/packages/docusaurus-theme-common/src/contexts/doc.tsx#L47-L56

But I feel like it may have something to do with the way we load the stored filters:
https://github.com/motion-canvas/motion-canvas/blob/528e2d5a0abec99819e022d2848b256ece9f869a/packages/docs/src/contexts/filters.tsx#L15-L23

In my case with counters, switching to `useIsBrowser` helped, because during hydration it's still set to `false`, then another re-render happens with its value set to `true`.
Maybe Docusaurus expects the initial state of the application to be exactly the same as the SSR version?

**Comment by WaldemarLehner** [comment]
![image](https://user-images.githubusercontent.com/27686785/218481970-d9bfdbf2-5a43-4f9e-9440-37df03d34fbc.png)

I think this is something on Docusaurus' End. The props are getting passed to their TOC Component correctly, as can be seen by the Debugger on the Right. 

If I could hazard a guess, I think that their list of TOC values is *not* reactive, while the size of the passed list is.

**Comment by WaldemarLehner** [comment]
I managed to hack a ""fix"" for this issue by basically letting the hydrated page ignore the filters on the first run, and then apply filters with `useEffect`. It is… dirty, but maybe that's the best solution we have here.

**Comment by WaldemarLehner** [comment]
I can create a PR if this *solution* works for you.
