### ISSUE TITLE
Support glob for project files

### ISSUE THREAD

**Issue by aarthificial** [motion-canvas/motion-canvas#324]
**Description**
Currently, all project files need to be manually listed in `vite.config.ts`

**Proposed solution**
Make the `project` option support the glob pattern.

**Considered alternatives**
It's possible to do this on the client side using the `glob` package as presented by @ksassnowski on [our Discord server](https://discord.com/channels/1071029581009657896/1073222950028845138/1073623773258973326):
```ts
// vite.config.ts
import glob from "glob";

export default defineConfig({
  plugins: [
    motionCanvas({
      // Will automatically grab all top-level folders inside `./src/projects/` and 
      // expose them as projects. These folders should contain an `index.ts` file 
      // that exports the project configuration.
      project: glob.sync("./src/projects/*"),
    }),
  ],
});
```
But it would be helpful to support this out of the box like most js libraries.

**Comment by ksassnowski** [comment]
Just in case anyone reads this and wants to follow my suggesting in the meantime: I actually wouldn't recommend naming the project files just `index.ts` as that would cause them to all show up as `index` in the project overview. Motion Canvas uses the _file name_ for its routing and not the `name` defined inside the project file as I had originally assumed.

**Comment by aarthificial** [comment]
In relation to using the project name: #297

**Comment by WaldemarLehner** [comment]
vite supports `import.meta.globEager(...)` to load all files that match a certain glob.

I am not sure if this feature is restricted for when you are running vite as a build tool. I ill give it a try and report back.

Docs: https://vitejs.dev/guide/features.html#glob-import

**Comment by WaldemarLehner** [comment]
Okay, so `import.meta.glob` can be used, just not in vite's config file.

**Comment by WaldemarLehner** [comment]
> But it would be helpful to support this out of the box like most js libraries.

I believe that having a separate template when running `npm init @motion-canvas` could be a good solution.
That template would then simply depend on `glob` and import the directories as shown in the first comment.

Having separate templates also makes sense because you generally have different file structures for a "single-project" and a "multi-project" repository.

something like 
```
src 
   — projects
       — project1.ts
       — project1
            — scenes...
       — project2.ts
       — project2
            — scenes...
```
comes to mind.


Only issue I found with using glob is that you need to restart the server for it to find newly created Projects.


I made a quick example repo using `glob` 
https://github.com/WaldemarLehner/motion-canvas-multi-project-example

**Comment by aarthificial** [comment]
The problem with templates is that they can't be used to migrate an already existing project.
I imagine a lot of people will start with just a single project and then decide to add more.
Having native support for this is a good QoA feature that shouldn't be difficult to implement/maintain.

**Comment by guifeliper** [comment]
I am working on this feature

**Comment by MarvinJWendt** [comment]
If anyone is interested in a "dirty, but it works" solution, I made this script as a workaround until the feature is shipped:

```ts
import { defineConfig } from 'vite';
import motionCanvas from '@motion-canvas/vite-plugin';
import * as fs from 'fs';

let projects: string[] = [];

// File structure must be ./src/projects/{projectName}/{projectName}.ts
fs.readdirSync('./src/projects').forEach(file => {
  projects.push(`./src/projects/${file}/${file}.ts`);
});

export default defineConfig({
  plugins: [motionCanvas({
    project: projects,
  })],
});
```

**Comment by rmhartog** [comment]
I noticed the adopt-me label on the PR and created a new one with some changes, crediting @guifeliper's initial work.
