### ISSUE TITLE
Adding an error or warning when using the same name for an event.

### ISSUE THREAD

**Issue by Thomsr** [motion-canvas/motion-canvas#326]
**Description**
What problem does it aim to fix?
Prevents using the same event name which could mess up the `.meta` file.

What benefits does it bring?
No more forgetting which names you have already used for events. And when you do accidentally use the same name, your other events do not change their timing.

**Proposed solution**
Adding a check in the `TimeEvents.ts` file in the `register` function if the event name has already been used in the `registeredEvents` Record.

**Considered alternatives**
There are no alternatives, unless you don't mind remembering every event name you have used.

**Comment by aarthificial** [comment]
Closed by #341
