### ISSUE TITLE
Add support for a camera

### ISSUE THREAD

**Issue by ksassnowski** [motion-canvas/motion-canvas#328]
## Description

In animations, it is often useful to move, scale or transform the entire viewport in order to focus on specific elements of a scene. For this reason, I propose to add the concept of a "camera" to Motion Canvas.

## Proposed solution

I have already [implemented](https://github.com/ksassnowski/motion-canvas-camera) a `CameraView` component and published it as a separate npm package. Even if we decide to implement it a different way, I think it serves as a good reference implementation. It also showcases what can be possible with a component like this. The implementation is surprisingly simple for how powerful it is.

The main idea is that the only thing that ever gets moved or transformed is the camera component itself. So when we want the camera to "zoom in" on a specific element, we're just moving the camera's position and scale so that the element we're trying to focus on will be at the camera's origin in the parent space.

```tsx
const camera = createRef<Camera>();
const circle1 = createRef<Circle>();
const circle2 = createRef<Circle>();

view.add(
  <Camera ref={camera}>
    <Circle ref={circle1} />
    <Circle ref={circle2} />
  </Camera>
);

yield* camera().zoomOnto(circle1()); 
yield* camera().zoomOnto(circle2()); 
```

Since I recently found out that you can embed videos in GitHub, here's a video that shows what's actually going on.

https://user-images.githubusercontent.com/5139098/218316050-c68f1e27-5133-44b7-8fc0-97a1b5faa9ac.mp4

This also works for children that are more deeply nested inside the camera's tree.

Any component that is not a child of the camera (either direct or transitive) won't get transformed. This would also allow you to add things to the scene at a "fixed" position.

### DX considerations

While I like the simplicity of using a component. Having to always manually add it to the scene feels a little clunky. Another potential pitfall is that when adding new components to the scene, the user would have to remember to add them to the _camera_, not the _view_.

```tsx
export default makeScene2D(function* (view) {
  const camera = createRef<Camera>();
  const rect = createRef<Rect>();

  view.add(
    <Camera ref={camera}>
      <Rect ref={rect} position={[300, 200]} />
    </Camera>
  );

  // Whoops, this is now not part of the camera.
  view.add(<Circle />);
});
```

My suggestion would be to add a new function `makeCameraScene2D` that can be used instead when creating a new scene. This function would then provide a `CameraView2D` to the scene's generator function that already has a camera built-in at the top level.

```tsx
export default makeCameraScene2D(function* (view: CameraView2D) {
  const rect = createRef<Rect>();

  // Will add it to the view's camera instead of adding it to the 
  // view directly.
  view.add(
      <Rect ref={rect} position={[300, 200]} />
  );

  // Adds the component to the view's camera, as expected
  view.add(<Circle />);

  // Access the camera via the view
  yield* view.camera.centerOn(rect());
});
```

This should be a fairly simple change to implement. The `CameraView2D` would probably look something like this

```ts
class CameraView2D extends View2D {
  public readonly camera: Camera;

  public constructor(props: LayoutProps) {
    super(props);
    this.add(<CameraView ref={makeRef(this, camera)} width={"100%"} height={"100%"} />);
  }

  public override add(node: ComponentChildren): this {
    // By default, add nodes to the camera.
    return this.camera().add(node);
  }

  // Provide a way for elements to be positioned "statically", i.e. have them
  // be unaffected by the camera's movement.
  public override addStatic(node: ComponentChildren): this {
    super.add(node);
  }

  // Do the same with insert
}
```

Doing this would still allow users to add additional camera's to the scene if they want.

## Considered alternatives

I initially tried implementing a camera by directly manipulating the main canvas element itself. That actually turned out to be more complicated to implement–and as a result, more error prone–as well as less flexible than simply having a `CameraView` component. 

By having the camera as a regular component, you can do things like controlling the size of the camera's viewport or  having multiple cameras in the same scene. If you're feeling especially saucy, you could theoretically even nest cameras within each other for maximum migraines.

## Additional context

This was inspired by the [`MovingCameraScene`](https://docs.manim.community/en/stable/reference/manim.scene.moving_camera_scene.html) from Manim.

**Comment by aarthificial** [comment]
I really like this idea, but I'm not sure if the contents visible by the camera should be its children.
Having used some three.js, I'd expect the camera to take a reference to the scene it's supposed to render:
```tsx
export default makeScene2D(function* (view) {
  const scene = (
    <Node ref={scene}>
      // contents to render
    </Node>
  );

  view.add(
    <Camera view={scene()} />
  );
});
```
The added benefit is that you could have two cameras showing the same thing from different positions.
(Unless you can already do that with your proposition and I just don't know how)

`makeCameraScene2D` could then receive two arguments, where `view` is just a simple node:
```ts
export default makeCameraScene2D(function* (view, camera) {
  // ...
});
```

Also, maybe instead of adding `makeCameraScene2D` we could just make the camera always be there for `makeScene2D`?

**Comment by ksassnowski** [comment]
I like the idea of passing the scene to the camera. Would the camera then simply render the scene, i.e. `add` them to the camera's layout? Because that would essentially create a copy of the each element, right?

**Comment by ksassnowski** [comment]
For instance, I'm not sure how a situation like this would work internally

```tsx
const camera1 = createRef<Camera>();
const camera2 = createRef<Camera>();
const circle = createRef<Circle>();

const scene = (
  <Node>
    <Circle ref={circle} />
</Node>
);

view.add(
  <Camera ref={camera} view={scene} />
  <Camera ref={camera2} view={scene} />
);

camera1().zoomOnto(circle());
camera2().zoomOnto(circle());
```

My understanding is that `circle` would be a reference to the same `Circle` node. Can the same node be added to different elements? What exactly would `circle().position()` be in that case?

**Comment by aarthificial** [comment]
`circle().position()` would be [0, 0]
The thing is, we don't need to add the nodes to the camera. 
The camera can just call the `render` method of the scene and pass it the rendering `context`, without modifying the hierarchy.

**Comment by ksassnowski** [comment]
I did a quick test on this where I overrode the camera's render method to look like this

```ts
public override render(context: CanvasRenderingContext2D): void {
  super.render(context);
  // this.scene() is the view passed to the camera
  this.scene().render(context);
}
```

This seems to .. almost work. My custom components get rendered for some reason, but none of the built-in components show up.

```tsx

const scene = (
  <Node>
    <Rect width={300} height={300} fill={"hotpink"} position={[0, 100]} />
    <Circle ref={circle} width={120} height={120} fill={"slategray"} />
    <PixelLine
      lineWidth={8}
      stroke={"bisque"}
      points={() => [[0, 0], endPoint()]}
    />
  </Node>
);

view.add(
  <>
    <Rect
      height={700}
      width={900}
      radius={18}
      justifyContent={"center"}
      alignItems={"center"}
      fill={"#101010"}
      position={[-480, 0]}
      smoothCorners
    >
      <CameraView ref={camera} scene={scene} width={900} height={700} />,
    </Rect>
  </>,
);
```
<img width="596" alt="CleanShot 2023-02-12 at 17 15 05@2x" src="https://user-images.githubusercontent.com/5139098/218322856-edc8447c-93d4-456a-b5e0-bb47b8aa7b90.png">

**Comment by ksassnowski** [comment]
My assumption is that since the nodes never got added to the scene, these elements don't actually have a size yet.

**Comment by ksassnowski** [comment]
Alright, got it 👌 

https://user-images.githubusercontent.com/5139098/218334556-d6930087-ed31-445e-9ec0-015dc8a7d040.mp4

I also like the suggestion of always providing a camera when using `makeScene2D` as the second parameter since it's not going to affect the animation if you don't use it. 

If it's ok with you, I'd go ahead with the implementation. My plan would be this:

- Implement a `Camera` component based my current component but stripped down to only the essentials, like `zoom`, `shift`,  `rotate` and the various `reset` methods. 
- I'd like to include two convenience methods `centerOn` and `zoomOnto` since these are really common operations to perform. 
- More complex features like following a path can always be added later and I'd rather not have the initial PR be massive. Especially since splines and Bézier curves are still an open topic. Especially since with the methods mentioned above, it's already possible to implement all of these things in userland.
- Adjust `makeScene2D` so it always includes a camera and pass it as the second parameter to the generator function
- Add a section in the docs on how to use the camera (also known as "my least favorite part")

Any objections?

**Comment by ksassnowski** [comment]
So one thing I'm kind of stuck on is how providing a default camera in `createScene2d` would work when the camera now requires a scene to be passed to it. I was hoping the user could avoid having to manually interact with the camera except for moving it around.

**Comment by ksassnowski** [comment]
So from a technical perspective, screen-fixed elements wouldn't technically be rendered by the camera at all but by the view itself. Anything not rendered/rendered outside the camera won't be affected by the camera's transform and so will appear to be fixed.

> Does absolutePosition refer to the scene or the camera view?

`absolutePosition` will always refer to world space, i.e. the scene.

**Comment by chris-findlay** [comment]
I guess my confusion is that if the camera references the scene, where does one put components that are outside the camera's view, and I think I also missed how the camera is added to the scene if it's not the whole viewport.

**Comment by ksassnowski** [comment]
The camera is just a component, so you would add it the same way you add any other component.

```tsx
export default makeScene2D(function*(view) {
  const scene = (
    <Node>
      <Text text={"Hello, world!"} />
    </Node>
  );

  view.add(
    <Camera scene={scene} />
  );
});
```

Any node that gets added to `view` instead of `scene` will be screen-fixed as it's not part of the scene that the camera is showing. This allows you to potentially have multiple cameras in the same scene like in my last video above. The code block on the left and the two cameras are children of the top-level view (i.e. they're siblings). The scene shown inside the cameras is a separate node that gets passed to both cameras as the `scene` parameter like in the code example above.

What I'm trying to do now is figure out a way so the user doesn't always have to manually add a camera to every scene as that feels a bit clunky. There should be an implied top-level camera that by default shows everything inside `view`. This would be a completely opaque change as the behavior from the point of view of the user would stay exactly the same. Except that they now also have the ability to move the view's camera around.

I'm basically trying to figure out the logistics of how exactly the scene would have to get set up internally if the camera now always requires an explicit view passed to it. It looks like I'll end up with a circular dependency between the view and the camera:

- Camera is part of the `View2D` (i.e. a top-level child)
- Camera always needs an explicit view to render
- Camera should always render the `View2D`
- ???

**Comment by chris-findlay** [comment]
Ok.  It's the distinction between view & (camera) scene that I'd missed.

**Comment by ksassnowski** [comment]
@aarthificial Do you have any more thoughts on this, or can I start with the implementation?

**Comment by aarthificial** [comment]
No, please feel free to start with the implementation.
