### ISSUE TITLE
Preview zoom and centering

### ISSUE THREAD

**Issue by piano1029** [motion-canvas/motion-canvas#329]
**Description**
Currently the only way to center the view of the preview is scrolling and dragging it manually, this isn't very easy to use (especially with broken scroll wheels like mine).

**Proposed solution**
A dropdown with "fit", "1x", "0.5x"... options to automatically size and center the preview would be great.

**Considered alternatives**
An alternative solution would be to add dragging stops (like in Photoshop when dragging an object) to center align it.

**Comment by exdeejay** [comment]
NB: hotkeys already exist to do this currently, here's the list:
`0` - Resets viewport and zoom level
`'` - Enables the grid
`=` - Zooms in
`-` - Zooms out 

A visual element would be a good addition, though.

**Comment by aarthificial** [comment]
Closed by #531
