### ISSUE TITLE
Podcast Inquiry

### ISSUE THREAD

**Issue by hipstersmoothie** [motion-canvas/motion-canvas#347]
Hey @aarthificial!

I think you work here is amazing! Such a natural fit for an animation API.

I didn't know how to reach you otherwise but would you be interested in coming on devtools.fm and talking about the development of this project?

**Comment by aarthificial** [comment]
Hi!
Unfortunately, I'm not able to participate in podcasts and other forms of collaboration due to personal issues.
Nevertheless, thanks so much for the invite, I really appreciate it!
