### ISSUE TITLE
why ttsc

### ISSUE THREAD

**Issue by lihqi** [motion-canvas/motion-canvas#358]
(https://github.com/motion-canvas/motion-canvas/blob/fc4ee5d028312904ed9e11c5341ac00f36e7242b/packages/vite-plugin/package.json#L12)

Great project ! 
But i cant understand this line

**Comment by aarthificial** [comment]
`ttsc` is a command provided by [ttypescript](https://www.npmjs.com/package/ttypescript) that lets us use custom transformers when building packages.
We use that to support markdown in our log messages.
