### ISSUE TITLE
Add "loopUntil" flow function

### ISSUE THREAD

**Issue by squigglesdev** [motion-canvas/motion-canvas#362]
**Description**
Feature request: Add a "loopUntil" flow function
This will act like the "loop" function, replacing the "iterations" number with an event.
It would allow for more fine tuning in the editor as to when something will happen, and up until that point, something else will be going on.

**Proposed solution**
Here is an example of the way the "loopUntil" function would work:
```tsx
// Something vibrates until it explodes (example)
yield * loopUntil(
	'Explode', // "Explode" event
	circle().position.x(-10, 0.2).to(10, 0.2) // To repeatedly occur until event
);
```

**Considered alternatives**
I have considered simply allowing the "waitUntil" function as an "iterations" parameter, but I feel this would be confusing, so should be done as highlighted above, in the same way the "waitFor" and "waitUntil" functions are separated.

**Comment by aarthificial** [comment]
Something like this should already possible with threads:
```ts
// start the loop concurrently:
const task = yield loop(Infinity, function* () {
  // animate something
});

// wait for the event:
yield* waitUntil('event');

// stop the loop:
cancel(task);
```
(Threads are still undocumented, unfortunately)

**Comment by squigglesdev** [comment]
That makes sense. I was sure that there was definitely a way to do this, just not in the way that I thought. Thanks. However I still believe that (for beginners like myself) a loop until or while type loop would be handy in these types of situations. Up to you though. I will use this technique for now.

**Comment by squigglesdev** [comment]
I'm implementing this in #418.
