### ISSUE TITLE
Changing the order of scenes during transition

### ISSUE THREAD

**Issue by aarthificial** [motion-canvas/motion-canvas#369]
**Description**
Currently, the next scene is always rendered on top of the current one during transitions.
Certain effects require this order to be reversed or change mid-animation. 

**Proposed solution**
Extend `useTransition` with a third argument specifying the order:
```ts
useTransition(
  prevCtx => {},
  nextCtx => {},
  true, // previous on top
);
```
It should accept a `SignalValue` to make changing order mid-animation possible:
```ts
useTransition(
  prevCtx => {},
  nextCtx => {},
  () => scale.x() > 0.5,
);
```

**Comment by monstajoe2002** [comment]
I would like to work on this issue please

**Comment by rmhartog** [comment]
Interested in putting together a PR for this.
