### ISSUE TITLE
Support cardinal points 

### ISSUE THREAD

**Issue by pragdave** [motion-canvas/motion-canvas#391]
**Description**

I quite often want to position nodes relative to other nodes. Most often, though, this position is something like "new rectangle to the right of this other rectangle". I also find it useful is this relationship is dynamic: resize the original, and the new moves accordingly.

Of course this can be done by adding or subtracting ½ width and or height, but that can get verbose and can hide the simpliciy of the intent.

I suggest adding 9 attributes to `Layout`: `n`, `ne`, `e`, `se`, `s`, `sw`, `w`, `nw`, and `c`. Each is a `SignalValue<PossibleVector2>`. 

`.c` is an alias for `position`. The others are calculated on-the-fly from the position and the node's shape. The base implementation would use the client rectangle, but shapes such as `Circle` would override this to provide specific implementations for the 45° points. 

This would let us write code such as

~~~ tsx
<Line points={[ r1().e, r2().sw ]} />
~~~

 or, to create a string of rectangles diagonally down and to the right

~~~ tsx
let last = new Vector2([100,100])
const boxes = []
for (let i = 0; i < 10; i++) 
  const ref = createRef<Rect>()
  const rect = <Rect ref={ref} nw={last} width={20} height={30} .../> 
  last = ref().se
  boxes.push(ref)
}
~~~

### Some History

I first saw this in the `pic` language in the 1970s. To my mind, `pic` still sets a high-bar for constraint-based layout.

**Comment by strau0106** [comment]
I agree, this isn't hard to implement and would improve UX (or in this case DX, I'm not sure what it is here, because its DX and UX at the same time?) drastically imho. However I wouldn't use North, East, South etc., but top, bottom, left, right, because NESW suggests a top down view but MC for me feels more like a horizontal viewing experience.

**Comment by aarthificial** [comment]
I agree something like this could be useful.
The proposed names are abysmal though. I understand that you probably used another software with this naming convention and it feels intuitive to _you_, but it's not intuitive to anyone else.

Agree with @strau0106, we'll go for `top`, `topRight`, `right`, etc. to match our `Origin` enum:
https://github.com/motion-canvas/motion-canvas/blob/1c2aa550bf898adc761ee58de1d37136a1551e72/packages/core/src/types/Origin.ts#L15-L25

**Comment by aarthificial** [comment]
Also -2 points for not using the template

**Comment by strau0106** [comment]
Since this is much quicker to implement than undo redo, I would quickly add those properties before going to the undo redo stuff.

**Comment by strau0106** [comment]
should the cardinal points be absolute or relative? I persume absolute would be more useful, or just both?

**Comment by aarthificial** [comment]
My quote from Discord for the record:
> Also, yes, they should be relative
And by that I mean in parent space
For now let's not add absolute variants bc I think I have an idea for a better api

**Comment by pragdave** [comment]
> Also -2 points for not using the template

I did. I just deleted the stuff where I had nothing to say :)

**Comment by ksassnowski** [comment]
> Agree with @strau0106, we'll go for top, topRight, right, etc. to match our Origin enum

So would `top` refer to screen `top` or coordinate space `top`? Intuitively, I'd assume that `top` and `bottom` would refer to the actual top and bottom of the node and not positive `y` or negative `y`.

**Comment by aarthificial** [comment]
Top in MC means `y = -1`
https://github.com/motion-canvas/motion-canvas/blob/1c2aa550bf898adc761ee58de1d37136a1551e72/packages/core/src/types/Origin.ts#L75-L80

**Comment by juliusv** [comment]
Yeah, as someone who is used from childhood to simple graphics libraries that take [x1, y1, x2, y2] for the 4 points of rectangles, this centered positioning in Motion Canvas also trips me up. Besides the initially mentioned use case of relative positioning between different rectangles, I'd also often like to do things like keeping one side of a rectangle in the same position while moving the opposite side (to effectively resize the rectangle in place, but anchored to one of its sides). This becomes cumbersome with the centered positioning, as you have to animate both the width and the position in just the right way at the same time.

**Comment by aarthificial** [comment]
@juliusv You can use the [`offset`](https://motioncanvas.io/docs/layouts#layoutoffset) property to change the origin of any Layout node.

Here's a simple example of a Rect whose left side is kept in place while resizing:
```ts
import {makeScene2D} from '@motion-canvas/2d';
import {Rect} from '@motion-canvas/2d/lib/components';
import {createRef} from '@motion-canvas/core/lib/utils';

export default makeScene2D(function* (view) {
  const rect = createRef<Rect>();

  view.add(<Rect ref={rect} offsetX={-1} size={320} fill={'white'} />);

  yield* rect().width(800, 2);
});
```

**Comment by juliusv** [comment]
@aarthificial Oh, great to know, thanks!
