### ISSUE TITLE
Simplify API documentation

### ISSUE THREAD

**Issue by pragdave** [motion-canvas/motion-canvas#392]
Right now the documentation for individual components is swamped by the methods inherited from Shape etc.

I'd like to discuss using the no-inherit plugin to strip these, so the API for `Circle` just shows circle-specific functions. 

Alternatively, we could create a plugin that groups methods in the side bar, showing first those in the actual  class, then those in the parent, then the grandparent, etc. Only the methods in the class itself would be listed in the main section. The other sidebar links would point to the documentation inside that particular class.

If this was of interest, I'd be happy to have a go at a PR for this.

Dave

**Comment by aarthificial** [comment]
Have you considered using filters?
![image](https://user-images.githubusercontent.com/64662184/220301877-37300ae0-1e6e-40a1-892a-890dd132ac23.png)

**Comment by aarthificial** [comment]
Closing this for now. Let us know if filters don't address your issue completly.
