### ISSUE TITLE
`CodeBlock` causes timeline issues after refreshing browser/editor

### ISSUE THREAD

**Issue by darksinge** [motion-canvas/motion-canvas#393]
**Describe the bug**
Refreshing the editor when using the `CodeBlock` component causes timing issues on the editor's timeline.

**To Reproduce**
1. Add the following code
    ```ts
    export default makeScene2D(function* (view) {
      const code = createRef<CodeBlock>();
      view.add(<CodeBlock ref={code}>{`const foo = ''`}</CodeBlock>);
      yield* code().edit(1)`const foo = '${insert("bar")}'`;
    });
    ```
2. Run `npm run serve`. An error appears that says
   ```
   Tried to access an asynchronous property before the node was ready. Make sure to yield the node before accessing the property.
   ```
3. Save the scene to trigger hot reloading and the error goes away. Video settings in the editor show there's a total of 30 frames.
4. Refresh the browser and the error reappears. Video settings show there's now only 24 frames, same as the range shown in the timeline. However, the playhead indicator moves past the "max range" in the timeline, stopping at 30 frames.

**Expected behavior**

The editor shows the same number of frames after refreshing the editor/browser. The playhead indicator does not move past the range visually indicated in the timeline.

**Console errors**
If applicable, add a screenshot of the errors displayed in the console of your browser (F12) or your terminal.

![CleanShot 2023-02-20 at 21 59 44](https://user-images.githubusercontent.com/14112087/220251828-b7a8606f-b450-43e6-b6af-3a0fd98bfd77.png)

**Package versions (please complete the following information):**

- core: 2.5.0
- ui: 2.5.0

**Additional context**

The problem only seems to occur when using `CodeBlock`. Other components such as `Circle` don't cause a problem.

**Comment by aarthificial** [comment]
This is a problem with missing documentation.
`CodeBlock` requires asynchronous resources, so it should be `yield`ed when added to the view:
```diff
export default makeScene2D(function* (view) {
  const code = createRef<CodeBlock>();
- view.add(<CodeBlock ref={code}>{`const foo = ''`}</CodeBlock>);
+ yield view.add(<CodeBlock ref={code}>{`const foo = ''`}</CodeBlock>);
  yield* code().edit(1)`const foo = '${insert("bar")}'`;
});
```

**Comment by aarthificial** [comment]
I created #395 to take care of this
