### ISSUE TITLE
Return to start frame on return key press

### ISSUE THREAD

**Issue by oujunhao** [motion-canvas/motion-canvas#399]
**Description**
It's annoying to have to click right at the beginning to see the start of the video. Having used other software like Logic Pro and Final Cut, I tried pressing the return key to go the beginning.

**Proposed solution**
Add an "Enter" handler in this [switch statement](https://github.com/motion-canvas/motion-canvas/blob/fbeb3924e58482ba589bfcde92ab34d8439e4f06/packages/ui/src/components/playback/PlaybackControls.tsx#L33) that requests the first frame.

**Considered alternatives**
The home key would also be a good candidate, though return is standard in other video editing tools like Final Cut and Premiere.

**Comment by oujunhao** [comment]
I can take this issue (I was going to go ahead and submit a pull request, but thought I'd check before doing that).

**Comment by aarthificial** [comment]
There are already shortcuts for this.
Pressing `SHIFT + LeftArrow` will also take you to the beginning of the animation. 
Analogically, pressing `SHIFT + RightArrow` will take you to the end.

**Comment by oujunhao** [comment]
Ah, I should have seen this when I was looking in that section of code.
