### ISSUE TITLE
Automatically convert to video

### ISSUE THREAD

**Issue by demipixel** [motion-canvas/motion-canvas#4]
**Description**
This is really just a quality of life. Presumably most people want a video and not merely a bunch of frames. You can run ffmpeg manually, but it would be nice if it were simply done for you.

`ffmpeg -framerate 60 -i 'frame%06d.png' -c:v h264 -pix_fmt yuv420p`

**Proposed solution**
Do a `fetch` after all frames are completed rendering. Node would then [try to convert to ffmpeg](https://stackoverflow.com/a/50736304/4384238).

**Considered alternatives**
Not sure if there are any—every single result for "convert images to video node" refer to ffmpeg.

**Comment by aarthificial** [comment]
The FFmpeg exporter is now available as a plugin:
https://github.com/motion-canvas/exporters#installation
