### ISSUE TITLE
Multiple audio support

### ISSUE THREAD

**Issue by Razkaroth** [motion-canvas/motion-canvas#419]
**Description**
Hi, I'm starting to use motion-canvas to make a series of college level math and physics courses.  And It's been great! However, these videos are long. A common occurrence is that I record the whole class, find out that I would like some scene to play slower or faster, or to introduce a new scene in the middle. Currently, I have to edit the audio file with external software. And then adjust the event timestamps.

This isn't that much of an issue, but sometimes, you want the audio to adjust to the animation instead of the animation adjusting to the audio.

I think the following features would be very helpful:
* The ability to pass an array of audios instead of a single one
* Set options for each audio:
  *  Offset (starting the _count_ at the end of the previous audio)
  * Padding (cut audio from the beginning or end of the audio)

**Proposed solution**
Perhaps it could look something like this:
``` typescript
interface IAudioFile {
    src: string;
    offset?: number;
    paddingStart?: number;
    paddingEnd?: number;
}

export default makeProject({
    ...,
    audio: [
        {
            src: './path/to/audio.mp3',
            offset: 2,
            paddingStart: 1,
            paddingEnd: 3,
        },
        {
            src: './path/to/audio2.mp3',
            offset: 5,
            paddingEnd: 1.2,
        }
    ]
});

```

**Additional context**
If posible, it would be awesome to adjust them in the browser by dragging them on the audio track. In this case, the provided values could be treated as the default or starting state of the audio timeline.

**Comment by aarthificial** [comment]
I'm sorry but this feature is extremly out of scope at the moment.
To quote [the intro page](https://motioncanvas.io/docs/):
> [Motion Canvas] is not meant to be a replacement for traditional video editing software.

Using a dedicated tool for audio editing is still the recommended way of doing this.
With hot module replacement, any changes you make to an audio file should be automatically reflected in Motion Canvas.
