### ISSUE TITLE
Transparent canvas is not cleared for each frame

### ISSUE THREAD

**Issue by cyberalien** [motion-canvas/motion-canvas#423]
**Describe the bug**
If in project settings background is set to `transparent`, each frame contains elements from last frame.

**To Reproduce**
Project settings:
```ts
export default makeProject({
  scenes: [example],
  background: "transparent",
});
```

Simple animation:

```ts
import { makeScene2D } from "@motion-canvas/2d/lib/scenes";
import { Circle } from "@motion-canvas/2d/lib/components";
import { createRef } from "@motion-canvas/core/lib/utils";

export default makeScene2D(function* (view) {
  const node = createRef<Circle>();

  view.add(<Circle ref={node} size={100} fill="red" />);

  yield* node().position([0, 0], 0).to([100, 0], 1);
});
```

**Expected behavior**
Expected canvas to be cleared for each frame.

**Package versions (please complete the following information):**

- core: 2.6.0
- ui: 2.6.0

**Comment by cyberalien** [comment]
Just figured out that I can just remove `background` from config, then it all works as expected.

However, error remains if background is semi-transparent, which results in cool but unintended motion blur. My guess is this is rare use case not worth fixing?

**Comment by aarthificial** [comment]
It's a silly oversight but should be fixed nonetheless
