### ISSUE TITLE
Support For Creating New Code Themes

### ISSUE THREAD

**Issue by K0dikas** [motion-canvas/motion-canvas#429]
**Description**
The `CodeBlock` theme system has been upgraded with the Shiki library. However, users may find the limited selection of 29 stock themes to choose from. Adding new themes through a PR to Shiki may not be a viable option since they rarely accept them. Having a wider selection of code themes is beneficial since it allows users to choose the most suitable one for their needs.

**Proposed solution**
The inclusion of a `theme.json` configuration file would allow users to create custom code themes that suit their needs. Additionally, implementing a global toggle option in `project.ts` would enable users to set the code theme automatically throughout their project, rather than manually setting the code theme for each individual scene.

**Considered alternatives**
One suggestion to improve the usability of the `CodeBlock` theme system is to add the actual `json` file of the code theme created by the original author locally, since `json` is already the configuration file. However, @Ross-Esmond  noted that themes are sourced from a CDN, making it unclear whether this alternative solution is viable.

**Comment by K0dikas** [comment]
I think it would be helpful to have a default `theme.json` file with modifiable hex values included in the `CodeBlock` theme system, rather than having to create it by the user. While it's technically possible to create a custom `json` file only if the user knows what there doing. So, having a default one would save time and effort. 

However, I'm not sure what the `theme.json` file would look like since version `3.0.0` has temporarily disabled code themes for the mean time and it's uncertain whether Shiki will be included in future updates. Cool concept though.

**Comment by BlenderDefender** [comment]
What about adding a property `themeStyle` (or something similar) to the CodeBlock Component, where the JSON Data can be directly passed to the component:
```js
<CodeBlock
     themeStyle={{keyword: "#f0ff0f", number: "#05963d"}}
/>
```
Implemented correctly, an editor like VSCode could provide Intellisense and help customizing the theme.

**Comment by Ross-Esmond** [comment]
That exists. The `theme` property takes an object where you can specify colors for some token types.
