### ISSUE TITLE
Vite/Motion Canvas fails to start after crash

### ISSUE THREAD

**Issue by jumangee** [motion-canvas/motion-canvas#431]
**Describe the bug**
Vite/Motion Canvas crashes and fails to start and the reason ist not clear - perhaps this is due to the use of video. When trying to restart (npn run serve) - error, only a complete restart of the system helps.

**To Reproduce**
I have two modules with video: intro with 9 seconds of video, and about2 with 5 seconds video. "Intro" faulted when it contained a video 5 seconds long, but after replacing it with a 9-second video, it became normal. Maybe this is the reason of crash.

```ts
export default makeProject({
  scenes: [intro, example, serieslist, about, about2, imported],
  background: '#141414',
  audio: audio,
  audioOffset: 0
});
```

```ts
import {makeScene2D} from '@motion-canvas/2d/lib/scenes';
import {Video} from '@motion-canvas/2d/lib/components';

import introVideo from '../media/import-ex.mp4';
import { createRef } from '@motion-canvas/core/lib/utils';
import { waitFor } from '@motion-canvas/core/lib/flow';

export default makeScene2D(function* (view) {
    const videoRef = createRef<Video>();
    view.add(<Video ref={videoRef} src={introVideo} />);

    videoRef().play();
    
    yield* videoRef().scale(1, 0).to(1.75, 2.5);

    yield* waitFor(6);
});
```

**Expected behavior**
Video in two different scenes both short - 5-7 seconds long

**Console errors**
```
> storyinheritance@0.0.0 serve
> vite


  VITE v3.2.5  ready in 1226 ms

  ➜  Local:   http://localhost:9000/
  ➜  Network: use --host to expose
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error: UNKNOWN: unknown error, watch
    at FSWatcher._handle.onchange (node:internal/fs/watchers:207:21)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (file:///M:/storyinheritance/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:51444:10)
    at NodeFsHandler$1._boundHandleError (file:///M:/storyinheritance/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:49922:43)
    at file:///M:/storyinheritance/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:49766:5
    at foreach (file:///M:/storyinheritance/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:49670:5)
    at fsWatchBroadcast (file:///M:/storyinheritance/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:49765:3)
    at FSWatcher.<anonymous> (file:///M:/storyinheritance/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:49814:9)
    at FSWatcher.emit (node:events:513:28)
    at FSWatcher._handle.onchange (node:internal/fs/watchers:213:12) {
  errno: -4094,
  syscall: 'watch',
  code: 'UNKNOWN',
  filename: null
}

Node.js v18.14.2
```

**Package versions (please complete the following information):**
+-- @motion-canvas/2d@2.6.0
+-- @motion-canvas/core@2.6.0
+-- @motion-canvas/ui@2.6.0
+-- @motion-canvas/vite-plugin@2.6.0
+-- typescript@4.9.5
`-- vite@3.2.5

**Additional context**
Windows 10x64
Chrome 110.0.5481.105 x64

Please, at least - teach me how to properly "reset" the frozen vite (motion canvas?) possibly holding port 9000, because for now i have to restart the entire computer for each experiment

**Comment by jumangee** [comment]
Now it does not start with the same error even after a reboot, even with completely removed video modules... I cant imagine what i did wrong :`(

**Comment by WaldemarLehner** [comment]
Not a fix for the issue, but maybe a fix for your repository :)

What happens if you delete node_modules, rerun `npm install` and start again?
If that fails, can you delete node_modules and also `package-lock.json` and try again?

As for your port issue, these instructions should help you kill a process by Port Number.
Note that you will need a terminal with admin privileges to run these commands :)

https://stackoverflow.com/a/55312303/7583353

**Comment by jumangee** [comment]
Reinstallation helped the clone project in the another folder, there it started without video modules. Nothing helps for the original project. In this case, the search on port 9000 gives an empty list, but the error is the same ((

**Comment by jumangee** [comment]
I'am sorry, looks like i found the reason: project folder was hosted at network-mounted disk. Moving the project to a regular disk helped and the project started even with video. It is a pity that there is a problem with the network drive, but at least it works)

**Comment by aarthificial** [comment]
Closing this for now since it's not a problem with Motion Canvas
