### ISSUE TITLE
Feature Request: Presentation mode

### ISSUE THREAD

**Issue by tlegoc** [motion-canvas/motion-canvas#441]
**Description**
Motion Canvas is great at rendering infographics and animation, it should work great as a diapositive/presentation tool.

**Proposed solution**
Adding events on the timeline that stops when reached, and resume on pressing space/right click/right arrow.
You can go back to the last even by pressing left arrow or left click.

**Considered alternatives**
JSX function that loops until a click is received.

**Comment by aarthificial** [comment]
Duplicate of #213
