### ISSUE TITLE
Disabling of 'layout' mode for child nodes

### ISSUE THREAD

**Issue by jumangee** [motion-canvas/motion-canvas#446]
**Description**
There is no way to "turn off" layout mode for child nodes. This leads to malfunction of contained components.
Example:
```
<Rect layout>
    <Rect
        fill={'#141414'}
        width={'40%'}
        height={60}
        paddingLeft={30}
        >
            <Node>
                <Switch initialState={true}/>
            </Node>
    </Rect>
    <Rect layout
        padding={10}
        fill={'#141414'}
        width={'60%'}
        height={60}
        direction={'column'}
        >
        <Text
            fontSize={32}
            fill={'white'}
            >
                Switch1
        </Text>
    </Rect>
</Rect>
```
Should add 'turned on' switch, but it shown as "off" (pin to left) with color of on-mode. And there no way to move it. In any case x-position of circle is negative. I thought making switch child to Node will help as said in docs, but no, its the same.
Switch perfectly works if add to scene as root node.

**Proposed solution**
```
<Rect
        layout={'unset'}/>
```

**Additional context**
![изображение](https://user-images.githubusercontent.com/3863733/221942643-21912a5c-33fa-4234-b815-e57b4a9fb05f.png)

**Comment by aarthificial** [comment]
You can disable layouting for child nodes with `layout={false}`

**Comment by jumangee** [comment]
Thanks! I've tried ={'false'}, {'unset'} and {null} :)
It would be good to add to docs such tips

**Comment by aarthificial** [comment]
> It would be good to add to docs such tips

I agree, made #449 for this purpose.
