### ISSUE TITLE
Create a `Polygon` component

### ISSUE THREAD

**Issue by andrie** [motion-canvas/motion-canvas#455]
**Description**

It would be helpful to have a component to draw various regular polygons, e.g. hexagons, octagons, etc.

**Proposed solution**

I propose this can be implemented by extending `Rect` and directly drawing to canvas by overriding the `getPath()` method.

You would pass these parameters to `PolygonProps`:

- `nSides` : number of sides of the polygon
- `angle`: the starting angle offset, in degrees

The `angle` parameter is necessary to control the orientation of the polygon.  For example, changing the angle of a hexagon can change the appearance so the hexagon is standing either on a point, or on a side.

This would be different from changing the `rotation` of the polygon.  I anticipate the need to have, for example, text inside a polygon (as a child node) but the text needs to remain horizontal, even if the angle of the polygon changes.

Note: the implementation draws the polygon inside a bounding circle (or ellipse). Thus it may appear that not all the vertices touch the bounding rectangle.

**Considered alternatives**

I tried to implement this by extending `Line` but the points of a `Line` don't animate well in canvas.

**Additional context**

I have working code and can prepare a PR, if this is useful.

Here is an example:

![motion-canvas-polygon](https://user-images.githubusercontent.com/479998/222133868-0eded308-c04b-4117-aa0d-f1e202d4201e.gif)

```
import {Polygon} from '../components/Polygon';

export default makeScene2D(function* (view) {

  const myPoly = createRef<Polygon>();
  const radius = createSignal(50);
  const nsides = createSignal(3);

  view.add(
    <>
      <Polygon 
        ref={myPoly}
        width={() => radius()}
        height={() => radius()}
        nSides={() => nsides()} 
        angle={() => 0.5 * 360 / nsides()}
        fill={'#ff0000'} 
        stroke={'#fff'}
        lineWidth={3} 
      />
    </>
  )

  yield * all (
    radius(100, 2) ,
    nsides(8, 2),
    myPoly().fill('#004400', 2)
  );
});
```

**Comment by aarthificial** [comment]
I think you should be able to extend `Shape` directly, instead of `Rect`. Even if we plan to support `radius` for polygons, since the implementation will be vastly different than that of `Rect` anyway.

One question though: What would happen if the provided `width` was different that the `height`?

**Comment by andrie** [comment]
Thanks, I can change to extend `Shape` quite easily.

If `height` is unequal to `width`, you get a distorted polygon.  For example, here is a hexagon where `height = 2 * width`:

![image](https://user-images.githubusercontent.com/479998/222192775-adb98ba0-5093-4f34-9d9d-ce80186959f8.png)

Oh, and by the way, if `nSides` is not an integer, you get an in-between polygon.  Here is a hexagon-ish polygon with 6.25 sides:

![image](https://user-images.githubusercontent.com/479998/222193409-ea90b1da-72f2-4fd1-92b1-e7c5583a24d5.png)

**Comment by aarthificial** [comment]
Alright, sounds good to me

**Comment by prabowomurti** [comment]
Do you any idea how to make an ellipse from a Polygon component? Or should we create another component ?

**Comment by andrie** [comment]
You can already use the circle component to create an ellipse.

 

https://motioncanvas.io/api/2d/components/Circle/

 

 

 

On Thu, 6 Jul 2023, 00:57 Prabowo Murti, ***@***.*** ***@***.***> > wrote:

Do you any idea how to make an ellipse from a Polygon component? Or should we create another component ?
