### ISSUE TITLE
Txt height slices overflow inconsistently

### ISSUE THREAD

**Issue by cyberalien** [motion-canvas/motion-canvas#465]
**Describe the bug**
If `Txt` element has height, which is lower than required to display whole text, it slices overflow inconsistently:
- If text is animated, overflow is cut.
- If text is not being animated, overflow is displayed.

https://user-images.githubusercontent.com/822287/222658306-19f624b9-679b-42db-b8e5-40cecd98344c.mp4

**To Reproduce**
Steps to reproduce the behavior
or a code snippet containing the scene that causes the problem:

```ts
import { makeScene2D } from "@motion-canvas/2d/lib/scenes";
import { Line, Node, Txt } from "@motion-canvas/2d/lib/components";
import { waitFor } from "@motion-canvas/core/lib/flow";
import { createRef } from "@motion-canvas/core/lib/utils";

export default makeScene2D(function* (view) {
  const textRef = createRef<Txt>();

  view.add(
    <Node>
      <Txt
        ref={textRef}
        text="Test / Text"
        fontFamily="Tilt Neon"
        fontSize={128}
        height={128}
        fill="#000"
        opacity={0}
      />
      <Line
        endArrow
        lineWidth={8}
        stroke="red"
        opacity={0.7}
        points={[
          [200, 200],
          [-15, 80],
        ]}
      />
    </Node>
  );

  // Animate text
  yield* textRef().opacity(1, 2);

  // Wait
  yield* waitFor(2);
});
```

Look at bottom of '/'. It is rendered outside of text height.

Font used in example is "Tilt Neon" from Google Fonts.

**Package versions (please complete the following information):**

- core: 3.0.0
- ui: 3.0.1

**Comment by AshishBarvaliya** [comment]
The purpose of using the height property is to restrict the amount of content that can be displayed within a box. If any type of fonts cause the content to overflow, we can adjust the height parameter to make it fit or remove it completely. There is no problem with the code that needs to be fixed.

Any thought? @aarthificial

**Comment by cyberalien** [comment]
> There is no problem with the code that needs to be fixed.

There is. Overflowing text is not cut when opacity is 1, but it is cut when opacity is below 1.

**Comment by AshishBarvaliya** [comment]
Ah, I see. It seems like the text is not perfectly vertically centered within the box.

**Comment by aarthificial** [comment]
The current behavior is generally correct. The text gets clipped when the opacity is smaller than `1` because the size of the cache canvas is determined (among other things) by the size of the node. If you want the text to always get clipped, you can use the `clip` property.

The bug is that the `Txt` node currently ignores the `clip` property.
