### ISSUE TITLE
Built in 3D support

### ISSUE THREAD

**Issue by debater-coder** [motion-canvas/motion-canvas#470]
**Description**
Sometimes it is helpful to be able to animate in 3D. I have seen that the deferred renderer example uses `three.js` to do so, but it seems there is quite a lot of plumbing to get it to work.

**Proposed solution**
A new package `@motion-canvas/3d` could provide built in tools for interfacing with 3D. Using this new API, it would be possible to do this:

```tsx
view.add(
   <Renderer>
      <Mesh geometry={...} material={...} />
   </Renderer>
)
```

**Comment by thegeeko** [comment]
I would be interested to work on this!

**Comment by aarthificial** [comment]
It's an interesting initiative but I personally don't have the time to work on this.
I don't think it needs to be a part of the main repo, though. If there are people willing to work on this, you can create a new repo and publish your own package. Here's a useful [repository template](https://github.com/hhenrichsen/motion-canvas-component-library-template).
