### ISSUE TITLE
Incorrect offset of slot in custom components

### ISSUE THREAD

**Issue by cyberalien** [motion-canvas/motion-canvas#474]
**Describe the bug**
Children passed as slot to custom component ignore offset of parent node.

**To Reproduce**
Code sample:

```ts
import { makeScene2D } from '@motion-canvas/2d/lib/scenes';
import { Node, NodeProps, Rect } from '@motion-canvas/2d/lib/components';

class Test extends Node {
	public constructor(props?: NodeProps) {
		super({
			...props,
		});

		this.add(
			<Node position={[100, 100]}>
				<Rect width={256} height={256} fill="rgba(128, 0, 0, 0.7)" />
				{this.children}
			</Node>
		);
	}
}

export default makeScene2D(function* (view) {
	view.add(
		<>
			<Test>
				<Rect width={256} height={256} fill="rgba(0, 128, 0, 0.7)" />
			</Test>
		</>
	);
});
```

Capture:
![000000](https://user-images.githubusercontent.com/822287/222920921-0f03cb67-8059-46c9-acef-6cdd07fc82b8.png)

**Expected behavior**
Expected both rectangles to be rendered in same place. Rectangles have identical size, position and parent, so they should be rendered identically.

**Package versions (please complete the following information):**

- core: 3.0.0
- ui: 3.0.1

**Comment by aarthificial** [comment]
This is the proper way of doing this:
```tsx
class Test extends Node {
  public constructor({children, ...props}: NodeProps) {
    super({
      ...props,
    });

    this.add(
      <Node position={[100, 100]}>
        <Rect width={256} height={256} fill="rgba(128, 0, 0, 0.7)" />
        {children}
      </Node>,
    );
  }
}
```
`this.children` is a signal. To get the actual array you'd need to call it: `this.children()`.
But it's better to simply extract the `children` from `props` so that they don't get added to the `Test` node. And instead place them whenever you want.

**Comment by cyberalien** [comment]
Thanks! That works.
