### ISSUE TITLE
Support LaTex Tweening

### ISSUE THREAD

**Issue by levirs565** [motion-canvas/motion-canvas#482]
**Description**
Math video need LaTex Tweening like in Manim.

**Proposed solution**
Parse MathJax rendered SVG and render each shape from SVG manually. Then we can animate each shape.

To tween LaTex we can use this function:

```js
yield * tex().tweenTex(target tex, duration)
```

**Considered alternatives**
Use external library for doing it.

**Additional context**

I have been working on this issue but PR are closed.

**Comment by levirs565** [comment]
This my experiment result:

https://user-images.githubusercontent.com/42236775/223397929-e4e9ebeb-782e-4eb5-a200-a5a1ad66fea7.mp4

To render Tex I use this methods:

- Convert Tex to SVG
- Parse SVG and extract all path
- Render path to canvas

To tween Tex I use this methods:

- Diff path between new and old tex
- Animate diff like in CodeBlock component

**Comment by aarthificial** [comment]
Thanks for making the issue

**Comment by levirs565** [comment]
I have new way to tweening Latex. First, we need create component  SVG Component.

SVG Component will convert SVG node into Motion Canvas Shape and add shape into component as children. We can animate SVG child using normal tweening. This component also can tween between two SVG. [Here is my SVG component code.](https://github.com/levirs565/motion-canvas-extras/blob/main/src/components/SVG.ts)

Latex component will inherit SVG component. We just need convert Latex into SVG.  To tween Latex we just tween the SVG component. [Here is my Latex component](https://github.com/levirs565/motion-canvas-extras/blob/main/src/components/AnimatedTex.ts)

This will not only resolve this issue. But also resolve [this issue](https://github.com/motion-canvas/motion-canvas/issues/509).

The result of this way is equal to old one.

I will merge my component into this repository when my SVG component can render most of SVG node.

**Comment by levirs565** [comment]
I have problem when placing my SVG component into Layout.

My SVG component is rendered correctly. However, other component inside layout is gone.

After some investigation. I found that, Layout component does not respect scale.

**Comment by aarthificial** [comment]
> Layout component does not respect scale.

This is by design, no layout engines support rudimental scaling/rotation - it would be a nightmare to handle.
The SVG node should respect the width and size properties in the same way images do.

> This component also can tween between two SVG

Note that your solution to tweening is vastly different than the one Manim uses. 
It's good enough for me but that's not what you mentioned in the description of the PR.
