### ISSUE TITLE
Documentation on Looping / Animating Multiple Objects

### ISSUE THREAD

**Issue by hhenrichsen** [motion-canvas/motion-canvas#483]
**Description**
Currently we have [flow](https://motioncanvas.io/docs/flow#all) that somewhat handles this case, but I think it would be useful to categorize some of the ways that you can loop multiple things at once, like these:

Functional:
```tsx
yield* all(Object.values(harpsRefs).map((circleRef) => {
    return circleRef().position.y(100, 2);
}));
```

For loops:
```tsx
for (const ref of Object.values(harpsRefs)) {
    yield ref().position.y(100, 2);
}
yield* waitFor(2);
```

Array-based for loops:
```tsx
const generators = [];
for (const ref of Object.values(harpsRefs)) {
    generators.push(ref.position.y(100, 2));
}
yield* all(...generators);
```

and whatever this cursed snippet is:
```tsx
const generators = [];
for (const ref of Object.values(harpsRefs)) {
    generators.push(ref.position.y(100, 2));
}
yield* generators;
yield* join(...generators);
```

just to give people an overview of how to solve some of these problems with generators (and give me a place to link when people ask this on the discord because it's happened twice now)

**Comment by aarthificial** [comment]
I agree that it's worth expanding the *Flow* guide with these.

The cursed snippet should go to the *Threading* guide (which doesn't exist yet but this is where `join`, `cancel`, `useThread`, etc. would be documented)

**Comment by aarthificial** [comment]
I made #484 for the *Threading* guide

**Comment by hhenrichsen** [comment]
I'll write this sometime this week unless someone wants to do it before me, in which case they can be assigned. Probably a good first issue, though.
