### ISSUE TITLE
auto-expansion of HEX colour to rgb(r,g,b) triggers on 3 digit values

### ISSUE THREAD

**Issue by ubidefeo** [motion-canvas/motion-canvas#513]
**Describe the bug**
when trying to enter a 6 digit HEX colour (i.e.: #ffaa88) on the third input the field replaces the value with its RGB counterpart, not allowing to enter the full 6(8 with alpha?) digits.

**To Reproduce**
Try to type in a HEX colour value in this box
<img width="500" alt="CleanShot 2023-03-13 at 07 54 05@2x" src="https://user-images.githubusercontent.com/1894487/224628653-3851c591-50ca-406a-9f6b-1a2502482367.png">
upon input of the third digit the colour will be automatically expanded to rgb(r, g, b)
<img width="455" alt="CleanShot 2023-03-13 at 07 55 11@2x" src="https://user-images.githubusercontent.com/1894487/224628874-de18767b-99c4-4219-8751-2c5d92782cc8.png">
preventing the previously wanted value to be used 

**Expected behavior**
the field lets the user manually enter a desired value for any of the following

* #RRGGBB
* #RRGGBBAA
* rgb(r, g, b)
* rgba(r, g, b, a)

**Package versions (please complete the following information):**
I can only see `3.2.0` at the bottom right, not sure where core and UI versions are to be retrieved from

**Comment by aarthificial** [comment]
Closed by #515

**Comment by aarthificial** [comment]
> I can only see 3.2.0 at the bottom right, not sure where core and UI versions are to be retrieved from

You can click on the version to copy detailed information about all pacakges
