### ISSUE TITLE
Txt wrapping not working

### ISSUE THREAD

**Issue by JulioHC00** [motion-canvas/motion-canvas#517]
**Describe the bug**
Enabling `textWrap` in a `Txt` and setting a `width` results in what looks like a wrapped bounding box for the object, but the text doesn't wrap.

**To Reproduce**
Simple scene to reproduce the problem

```ts
import {makeScene2D} from '@motion-canvas/2d/lib/scenes';
import {Txt} from '@motion-canvas/2d/lib/components'

export default makeScene2D(function* (view) {

  view.add(
    <Txt
      fontFamily={'Noto Sans'}
      fontSize={36}
      width={1000}
      fill={"black"}
      lineHeight={50}
      letterSpacing={2}
      textWrap={true}
    >
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed nunc fringilla, blandit diam eu, dapibus sem. In sapien tellus, consectetur non gravida id, eleifend ac odio. Vivamus eu mauris convallis, faucibus elit fringilla, elementum nibh. Cras tristique orci sit amet sem laoreet, et dictum nunc pulvinar. Etiam sit amet mollis eros, vitae feugiat mauris. Integer et dui interdum, laoreet purus et, placerat libero. Nunc dapibus leo in elit tempor, in iaculis urna luctus. Donec sodales nibh at erat pretium porttitor nec vel mi. Etiam sagittis nisl non tortor imperdiet, in varius lorem porttitor. Aliquam laoreet tellus vel odio lobortis, id convallis purus sodales. Cras scelerisque ornare massa pretium ultrices.
    </Txt>
  )
});
```

**Expected behavior**
Text would wrap at a width of 1000

**Console errors**
![image](https://user-images.githubusercontent.com/81090346/224782119-36bf189f-3ddb-48d9-96fb-5891598f8195.png)

**Package versions (please complete the following information):**

- core: 3.2.0
- ui: 3.2.1

**Additional context**
None

**Comment by aarthificial** [comment]
Like the message says: `Wrapping is not supported`
Firefox doesn't support [`Intl.Segmenter`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter) which we currently use for splitting text.
We could split the text into arbitrary characters when in Firefox, but that will only work with the Latin alphabet.
