### ISSUE TITLE
Can't assign port

### ISSUE THREAD

**Issue by micartey** [motion-canvas/motion-canvas#527]
**Describe the bug**

Normally, you can overwrite the port in the `vite.config.ts` file with

```
export default defineConfig({
  plugins: [motionCanvas()],
  server: {
    port: 3000
  }
});
```

Or just run `vite --port 3000`

But that doesn't work and always starts on port 9000

**To Reproduce**

Just follow the instructions

**Expected behavior**

The application runs on port 3000

**Package versions (please complete the following information):**

- core: ^3.2.0
- ui: ^3.2.1

**Comment by aarthificial** [comment]
Our plugin defines the port explicitly which is most likely causing the issue:
https://github.com/motion-canvas/motion-canvas/blob/25b30ed3861f46d72147335480912ce5f564be79/packages/vite-plugin/src/main.ts#L379-L381
