### ISSUE TITLE
Loops stop before scene transition, not after

### ISSUE THREAD

**Issue by gBasil** [motion-canvas/motion-canvas#533]
**Describe the bug**
When an infinite loop is active a la `yield loop(Infinity, () => {})`, the loop stops when the scene transition begins. This is an issue when you want something to keep animating until the transition finishes, and then dispose of the loop.

**To Reproduce**
1. Start a loop with `yield loop(Infinity, () => {})` that visibly animates something at the end of the first scene
2. Add a second scene, and add some sort of transition, like a slide.
3. Observe how the loop in the first scene stops, even when they're still visible.

**Expected behavior**
The loops from the previous scene will continue until the scene transition is complete, and then they will stop.

**Console errors**
N/A

**Package versions (please complete the following information):**

- core:  3.2.0
- 2d: 3.2.0

**Comment by aarthificial** [comment]
https://motioncanvas.io/docs/transitions#animate-when-transitioning

**Comment by aarthificial** [comment]
```ts
const task = yield loop(Infinity, () => {});
// ...
finishScene();
yield* join(task);
```

**Comment by aarthificial** [comment]
No worries!
