### ISSUE TITLE
Inline text style

### ISSUE THREAD

**Issue by blobinabottle** [motion-canvas/motion-canvas#540]
**Description**
Maybe I missed something but I didn't find a way to do inline styling of text. 

**Proposed solution**
Something like in tex  (ie: \color)? But ideally tweenable... 

**Considered alternatives**
Is it correct the only alternative way is to create multiple text objects for each style?

**Additional context**
If I missed that feature (which seems quite important) maybe docs need to highlight it bette?
+ thanks for the fantastic lib! 🤘

**Comment by aarthificial** [comment]
No you didn't miss that feature, we don't have it yet.
I think we should go more towards JSX though.
Perhaps something like:
```tsx
view.add(
  <Text>
    Some text with <Text fill="red">a different color</Text> here.
  </Text>
);
```
Tweening could then use the same mechanism as the rest of the library:
```tsx
const color = Color.createSignal('red');
view.add(
  <Text>
    Some text with <Text fill={color}>a different color</Text> here.
  </Text>
);
yield* color('blue', 0.3);
```
It would also be possible to provide some aliases, like:
```tsx
const B = props => <Text fontWeight={700} {...props}/>;
view.add(
  <Text>
    Some <B>bold text</B> here.
  </Text>
);
```
Tweening the contets of a text node could then be realized in the same way the new LaTeX tweening works (#539)
So it would be possible to do:
```tsx
const text = createRef<Text>();
view.add(
  <Text ref={text}>
    Some text with <Text fill="red">a different color</Text> here.
  </Text>
);
yield* text().text(
  <>Some <B>bold text</B> here.</>,
  2
);
```

**Comment by Gabryxx7** [comment]
I just wanted to mention that I managed to get a full Markdown parser working, and it should be easily extensible to add other features like underlining. So far the titles with # work well, so do lists, nested lists, inline bold (with proper text wrapping, not just two side-by-side Txt components). Multiple indented lists work ok too!

I actually also got an inline component working too, but there are a few more things I need to fix. All of these text blocks are inside a larger text component called `TextBlock` but all of them are just an extended version of `Txt` which I called `MDText,  the markdown gets parsed, then gets added to the shadow root DOM with css styles matching the Node `props` (which are signals like any other component props)

![Screenshot 2023-10-27 at 00 42 55](https://github.com/motion-canvas/motion-canvas/assets/6282055/50fe79ad-76cd-4fc3-9efb-6fc299fda228)

![Screenshot 2023-10-27 at 01 01 43](https://github.com/motion-canvas/motion-canvas/assets/6282055/b8949a76-43b6-4716-ab35-6f0750b8bd94)



```jsx
 <TextBlock>
{`
Hey just testing this *out*! 

## I'm an H2 title!

You can see that this works fairly *well* 
- you can even have lists
   - insides lists
      - with *bold* text
      - blank lines


      - ...and hopefully more!
`}
 </TextBlock>
```

**Comment by Mohammad9760** [comment]
the issue is completed. how can we achieve styling now?
