### ISSUE TITLE
Ambiguous indirect export

### ISSUE THREAD

**Issue by Arnau478** [motion-canvas/motion-canvas#543]
**Describe the bug**
When trying to use the `Img` 2d component, the page doesn't load and the console shows `Uncaught SyntaxError: ambiguous indirect export: Img`

**To Reproduce**
I did it with this code, but this also fails with the example given on the documentation, for using images.
```ts
import {makeScene2D} from '@motion-canvas/2d/lib/scenes';
import {waitFor} from '@motion-canvas/core/lib/flow';
import {Img, Layout} from '@motion-canvas/2d/lib/components';

import logo from '../../images/logo.png';

export default makeScene2D(function* (view) {
    view.fill("#391626");

    vies.add(<Img src={logo} />);

    yield* waitFor(5);
});
```

**Expected behavior**
Well, to not do that.

**Console errors**
![image](https://user-images.githubusercontent.com/61841960/226022235-ebc3fc63-473e-4995-8f23-fa082b69c9f5.png)

**Package versions**
- core: 2.6.0
- ui: 2.6.0

**Comment by aarthificial** [comment]
`Img` is a new name for the `Image` node introduced in version `3.0.0`:
https://motioncanvas.io/docs/migrating-to-3.0.0
You're still using v2 so you have to use `Image`.

**Comment by Arnau478** [comment]
Oh, sure! Sorry for the dumb issue!
