### ISSUE TITLE
Change the favicon of documentation to not be same as the editor

### ISSUE THREAD

**Issue by TheNextGuy32** [motion-canvas/motion-canvas#556]
The editor sharing the favicon with the documentation page has caused me constant micro-frustrations. I have 30+ tabs open, often with several tabs just of the documentation, and I never know which tab to click.

**Comment by aarthificial** [comment]
I'm open to suggestions for a dev-only icon.

As a workaround, you can change the favicon in your project file:
```ts
document.querySelector<HTMLLinkElement>("link[rel~='icon']").href = '...';
```

Side note:
People not following issue templates are causing me constant micro-frustrations.

**Comment by aarthificial** [comment]
The editor icon has been changed to a desaturated version:
![image](https://github.com/motion-canvas/motion-canvas/assets/64662184/d5e91ab2-f80f-4257-a458-3ac393da3d12)
