### ISSUE TITLE
Allow working with existing strings in CodeBlock

### ISSUE THREAD

**Issue by niosus** [motion-canvas/motion-canvas#560]
**Description**
Let's say I have a longer piece of code that I want to modify through the animations. It seems that at this time, I would have to copy the code over again and again in order to change certain parts of it. It would be cool if I could do something like "add insert to existing string"

The library functionality is simply amazing and if I were able to do the above it would really improve the graphics in the course that I am teaching.

**Proposed solution**
Considering that I have an example piece of code: 
```js
const code = `
  struct Foo {
    int number_of_lives_{kDefaultNumberOfLives};
    int happiness_{};
  };`

yield view.add(<CodeBlock ref={codeRef} language="cpp" code={code}/>);
```
It would be great is I could change it by doing something along these lines:
```js
yield* codeRef().edit(1.2) code + ${insert(`\n int main() { Foo foo; }`)};
```
If I understand correctly, for now I would need to copy the whole long string from before instead of the `code` variable in my example. Hope this is clear enough but please do not hesitate to ask me for any clarification should the idea not be clear.

**Considered alternatives**
I do not have enough introspection and knowledge about typescript (or javascript for that matter) to know if there might be some alternative that I am missing here, but I am open to suggestions.

**Comment by aarthificial** [comment]
You can use `codeRef().code()` to get the current code and use it in the string via `${}`:
```ts
import {waitFor} from '@motion-canvas/core/lib/flow';
import {makeScene2D} from '@motion-canvas/2d';
import {createRef} from '@motion-canvas/core/lib/utils';
import {CodeBlock, insert} from '@motion-canvas/2d/lib/components/CodeBlock';

export default makeScene2D(function* (view) {
  const codeRef = createRef<CodeBlock>();

  view.add(
    <CodeBlock ref={codeRef} language={'cpp'}>{`
struct Foo {
  int number_of_lives_{kDefaultNumberOfLives};
  int happiness_{};
};
  `}</CodeBlock>,
  );

  // this will insert the new line at the end:
  yield* codeRef().edit(1)`${codeRef().code()}${insert(`
int main() { Foo foo; }
`)}`;

  yield* waitFor(2);
});
```
The type system will tell you that it's not correct but the animation should actually work.
I'll fix the types in the context of this issue.

**Comment by niosus** [comment]
That sounds awesome! The type error threw me off, thanks for clarifications and for the great work! 🎉

**Comment by gk-patel** [comment]
This issue is closed, but still the context is relevant to my question so adding comment here.

Is it possible to iterate over an array ? 

  const newCode= [
    insert('# 2. Variables and arithmetic'),
    insert('x = 5'),
    insert('y = 10'),
    insert('sum = x + y'),
    insert('print(f"The sum of {x} and {y} is {sum}")'),
    insert(''),
  ]

And somehow use this variable and pass it to the codeRef().edit(1) ??

Thanks for your reply and the wonderful tool !!!

**Comment by aarthificial** [comment]
@gk-patel 
If I understood correctly that you want to show the lines one after the other in a loop then this is how you could achieve that:
```tsx
import {makeScene2D} from '@motion-canvas/2d';
import {CodeBlock, insert} from '@motion-canvas/2d/lib/components/CodeBlock';
import {waitFor, createRef} from '@motion-canvas/core';

export default makeScene2D(function* (view) {
  const codeRef = createRef<CodeBlock>();
  yield view.add(<CodeBlock offsetX={-1} ref={codeRef} />);

  const newCode = [
    '# 2. Variables and arithmetic',
    'x = 5',
    'y = 10',
    'sum = x + y',
    'print(f"The sum of {x} and {y} is {sum}")',
    '',
  ];

  for (const line of newCode) {
    yield* codeRef().edit(1, false)`${codeRef().code()}${insert(line + '\n')}`;
  }

  yield* waitFor(5);
});
```
