### ISSUE TITLE
Deselect convenience function

### ISSUE THREAD

**Issue by ErikRospo** [motion-canvas/motion-canvas#567]
**Description**
Currently, the only way to deselect code is to select between zero and infinity like `lines(0, Infinity)`. This is hard to read and doesn't effectively convey what the code does.  

**Proposed solution**
To deselect code, people could use a `deselect()` function.  
For example,  
`
yield * codeRef().selection(lines(1)); 
yield * codeRef().selection(deselect())
`  
The deselect function could just be an alias for `[[0,0],[Infinity, Infinity]]`  
**Considered alternatives**
While people could use the `lines(0, Infinity)` or `[[0,0],[Infinity, Infinity]]` syntax, these are longer and harder to read.

**Comment by niosus** [comment]
I would also like to have such a feature. An alternative API from my point of view could be to pass `null` into the range attribute, something like:
```js
yield * codeRef().selection(lines(1));  
yield * codeRef().selection(null);
```

**Comment by aarthificial** [comment]
You can use the [`DEFAULT` symbol](https://motioncanvas.io/docs/signals#default-values) to reset the value of any property.
In this case, the default value of `selection` is a range that overlaps everything so you can do:
```ts
codeRef().selection(DEFAULT);
```
Tweening also works:
```ts
yield* codeRef().selection(DEFAULT, 2);
```

**Comment by niosus** [comment]
@aarthificial would it be ok to add this to the docs? I find it much neater than the current recommendation involving `Infinity` 🤔
