### ISSUE TITLE
Store the operation on CodeBlock as a variable

### ISSUE THREAD

**Issue by niosus** [motion-canvas/motion-canvas#573]
**Description**
Sorry for bombarding you with these issues, and please don't spend too many cycles on this question - it might be completely dumb and I'm pretty sure I'm just doing something wrong here. This is slightly related to #560 

For now, when I need an `$edit` in long text, what I do is I split the text around the edit point.

Then, when I want to animate the code changes I end up doing the following:
```js
yield* codeRef().edit(duration, false)`long text ${edit(`before`, `after`)} long text`;
```

What I would like to be able to do instead is this: 
```js
const text_with_changes = `long text ${blah_edit} long text`;
yield* codeRef().edit(duration, false)`${text_with_changes}`;
```

**Proposed solution**
As TypeScript is not my first, second or even third language, I might be missing an obvious way to do things. Unfortunately I don't know it well enough to propose a feasible solution straight of the bat.

**Considered alternatives**
While I don't see many more viable alternatives here, I am very open to any suggestions.

**Comment by aarthificial** [comment]
I'm not sure I understand, but if what you want is to store the edit string and use it later, you can create a simple tag function to do so:
```ts
const store = (...args: [TemplateStringsArray, any]) => args;
```
And then use it as follows:
```ts
const text_with_changes = store`long text ${edit('before', 'after')} long text`;
yield* codeRef().edit(duration, false)(...text_with_changes);
```
