### ISSUE TITLE
Part of chroma-js export missing in built project bundle

### ISSUE THREAD

**Issue by sqpchris** [motion-canvas/motion-canvas#577]
**Describe the bug**
I've found an odd edge case when building a project (using `npm run build`) where the bundled Javascript file is missing some of the `chroma-js` package

**To Reproduce**
1) Create the following scene in a new motion-canvas project
```ts
import { Img, Rect, Txt } from '@motion-canvas/2d/lib/components';
import { makeScene2D } from '@motion-canvas/2d/lib/scenes';
import { waitFor } from '@motion-canvas/core/lib/flow';

export default makeScene2D(function* (view) {
  
  const data = {text: {header: "Hello"}}
  const {text} = data;
  
  view.add(<Rect opacity={1} layout={false}>
    <Img src={`test.png`} />
    <Txt fill={"#FAFAFA"}>{data.text.header}</Txt>
  </Rect>
  )

  yield* waitFor(5);
});
```

2) Disable `build.minify` in `vite.config.ts`
```ts
export default defineConfig({
  plugins: [motionCanvas()],
  build: {
    minify:false
  }
});
```
3) Run `npm run build`. Move the built file out of the dist folder

4) Comment out the follow line in the scene:
`const {text} = data;`

5) Run `npm run build`. Move the built file out of the dist folder

6) Compare the two build files. The first will have a block of `chromaExports` missing:
<img width="1908" alt="Screenshot 2023-03-25 at 17 25 05" src="https://user-images.githubusercontent.com/74988438/227732296-a21f6f80-a8ca-4d7c-bdb8-83389d0bb6b5.png">

7) Run each file through `motion-canvas-player`. The second will work, the first will throw this error:
```
Uncaught (in promise) TypeError: background.serialize is not a function
    at Stage.configure (Stage.ts:74:23)
    at X.updateSettings (main.js:715:5)
    at X.updateSource (main.js:678:22)
```
This is because the `chromaExports.Color.prototype.serialize` part of the bundle file is missing

**Package versions (please complete the following information):**
- core: 3.3.4
- ui: 3.3.4
- player: 3.3.4

**Additional context**
My current workaround is to `import "@motion-canvas/core/lib/types/Color"` in my scene

And finally, thanks for all the hard work that gone into making motion-canvas! It's a fantastic tool which has helped me greatly with one of my current projects 🚀

**Comment by aarthificial** [comment]
@StefanKreidel tagging you because it seems to be the same issue as in your https://github.com/motion-canvas/motion-canvas/issues/443#issuecomment-1478487124

**Comment by StefanKreidel** [comment]
Thanks for the tag @aarthificial. The workaround also works for me!
