### ISSUE TITLE
Adding script output render option

### ISSUE THREAD

**Issue by yuval-herman** [motion-canvas/motion-canvas#590]
**Description**
I believe at this point it's quite clear MC is being used quite extensively as a standalone video editor together with ffmpeg.
There are already a few issues opened about this such as:
#4 #364 #462 #488,
As well as #422
I think MC should embrace this use case for the sake of the community.

**Proposed solution**
I propose a new render option, that will output a script (bash, batch, etc...) that will run ffmpeg and compile all the output frames from the normal render into a video.
This will allow us to add audio strips, as well as extracting audio from embedded videos and re-adding it back to the output video.
I am aware of the stance @aarthificial has on MC not being a full fledged video editor, and for that reason I propose this will be implemented as a plugin, so as to keep MC "pure".
Another advantage of this method is allowing changes to video volume, which is currently irrelevant / impossible since it won't be exported, but is possible with ffmpeg.

**Considered alternatives**
I have considered using MLT files instead of generating custom shell scripts, however this seems counter intuitive since it requires a considerable amount of effort from both developers and users to install and set up MLT's framework.
I do think this should be considered however, since it is somewhat of a standard in the opensource world, and could potentially allow tight integration with existing open source editors such as kdenlive, flowblade, shotcut, [and more...](https://www.mltframework.org/projects/)

**Additional context**
Here are some relevant links:
[MLT framework's homepage](https://www.mltframework.org/)
[ffmpeg multi audio input with delays](https://superuser.com/a/1191664)

**Comment by aarthificial** [comment]
Seems like you've just repeated what I already said in #422. 
The official ffmpeg exporter will be implemented as part of #4.

If the point of this issue is to propose yet another exporter that will output a bash script instead of a video file then I don't really see the need for that.
Otherwise, this issue is a duplicate of #4.

**Comment by yuval-herman** [comment]
I think there is one key difference here. I have, of course already read al those other issues, bit none of them satisfied my specific need.
My use case is as follows:
I want to be able to use multiple videos as well as multiple audio tracks, while still having the flexibility of exporting images.
I think there is actually only one issue with MC as it is and it is audio track support. MLT caters exactly to my needs, however is a pretty big commitment.
I would be happy to explain myself further in the discord channel if you wish and edit the issue to be clearer. If you are not on board with me that is of course completely fine, I would'nt want to waste anyone's time!

**Comment by yuval-herman** [comment]
Very well, I will close this issue.
