### ISSUE TITLE
absolutePoints for <Line>

### ISSUE THREAD

**Issue by A-ZC-Lau** [motion-canvas/motion-canvas#604]
**Description**
We have `absolutePosition` and `absoluteScale`, but there's no direct way to use them with <Line>, and you have to calculate where exactly something is e.g. `Node().absolutePosition().x - viewWidth / 2` to get the actual x location of a node. 

**Proposed solution**
adding a `absolutePoints` allows us to easily just point directly to a Node no matter where it is in the world

**Considered alternatives**
don't think alternatives are needed

**Comment by aarthificial** [comment]
You can set the absolute position of your line to zero and then use the absolute positions of other nodes directly:
```tsx
import {makeScene2D} from '@motion-canvas/2d';
import {Circle, Line, Node} from '@motion-canvas/2d/lib/components';
import {waitFor} from '@motion-canvas/core/lib/flow';
import {createRef} from '@motion-canvas/core/lib/utils';
import {Vector2} from '@motion-canvas/core/lib/types';

export default makeScene2D(function* (view) {
  const line = createRef<Line>();
  const circle = createRef<Circle>();
  const circle2 = createRef<Circle>();

  view.add(
    <>
      <Node x={200}>
        <Circle size={50} fill={'red'} y={200} ref={circle} />
        <Circle size={50} fill={'blue'} y={-100} x={100} ref={circle2} />
      </Node>
      <Line
        ref={line}
        lineWidth={8}
        stroke={'white'}
        points={[circle().absolutePosition, circle2().absolutePosition]}
      />
    </>,
  );

  line().absolutePosition(Vector2.zero);

  yield* waitFor(5);
});
```
![image](https://user-images.githubusercontent.com/64662184/229493309-c2a3aca7-c043-4242-90bd-115871cff51d.png)

---

**Side note:**
The correct way of getting the position of a node in relation to the view is by using the view matrix:
```ts
const position = node().absolutePosition().transformAsPoint(view.worldToLocal())
```
