### ISSUE TITLE
Multiple docs for type appear incorrectly

### ISSUE THREAD

**Issue by gmile** [motion-canvas/motion-canvas#621]
**Description**

There appear to what look like syntax mistakes in the documentation for types.

For example, several examples on the [Types](https://motioncanvas.io/api/core/types) page are missing a matching opening curly bracket:

* https://motioncanvas.io/api/core/types#SerializedBBox

    ![image](https://user-images.githubusercontent.com/207112/231720555-90166f2b-be1d-48d7-acb6-6e56a93663b7.png)
* https://motioncanvas.io/api/core/types#SerializedSpacing

    ![image](https://user-images.githubusercontent.com/207112/231720375-6a7cd4ac-071d-456b-8244-340236550bcc.png)
* https://motioncanvas.io/api/core/types#PossibleColor

    ![image](https://user-images.githubusercontent.com/207112/231720771-c3e0ff35-53e0-482e-af27-e6e32be4c6df.png)

I was under impression docs for types are auto-generated. If that's the case, there may be some systemic issue in the auto-generating code that causes this class or issues to appear?

**Comment by aarthificial** [comment]
Chrome, Win 11:
![image](https://user-images.githubusercontent.com/64662184/231908427-03a45dac-7f5b-4034-954b-42a3b6d7bbcd.png)

Firefox, Win 11:
![image](https://user-images.githubusercontent.com/64662184/231908455-d13e0660-8919-4bb2-b405-45f861c1c083.png)

Brackets and commas are displayed using CSS `::before` and `::after` to support dynamic wrapping:
![image](https://user-images.githubusercontent.com/64662184/231908588-c7b878ed-9714-407d-9627-8338b251a387.png)
Maybe there's something about your browser/OS configuration that prevents them from being properly displayed?

**Comment by gmile** [comment]
Above screenshot were taken in macOS 13.3 + Chrome. Unfortunately, I didn't keep the exact the version they were taken with, but you can see the the Chrome on the screenshots was "mildly out-of-date".

The bracers display correctly now that the Chrome is updated. All good here, closing the issue :)

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/207112/232002795-9abb0cdb-b8c6-4c10-8abd-d8d714120ad3.png">
