### ISSUE TITLE
Use weakRef in Reference<T>

### ISSUE THREAD

**Issue by ccaven** [motion-canvas/motion-canvas#632]
**Description**
Currently, MC references are a fancy word for a closure. However, in projects that involve many references to the same object and lots of objects, it may cause issues with those references keeping the objects they reference from being garbage-collected.

Also, the TS definitions for references could be changed to separate functionality for readable and writable references. The motivation for this is that sometimes you want to return a read-only reference to something (e.g. the `this` object from within the `Node` class).
Note: this will NOT change how the public api for references work.

**Proposed solution**
First, use JavaScript's builtin [WeakRef](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef) class to store references under the hood (keeping public functionality the same).
```ts
export function createRef<T>(): MutableReference<T> {
    let weakRef: WeakRef<T> | null = null;

    const ref = (element?: T) => {
        if (element != undefined) {
            weakRef = new WeakRef(element);
        } else if (weakRef != null) {
            return weakRef.deref();
        } else {
            return null;
        }
    };
    
    return ref as Reference<T>;
}

export function createConstRef<T>(object: T): Reference<T> {
    let weakRef = new WeakRef(object);
    return () => weakRef.deref();
}
```

Second, split the TS interfaces from `ReferenceReceiver` / `Reference` into `Reference`, `MutableReference`:
```ts
export interface Reference<T> {
    (): T | null;
}
export interface MutableReference<T> extends Reference<T> {
    (element: T): void;
}
```

**Considered alternatives**
Pretty much any other change would break how the current api functions. In an ideal word, a reference would never be null, but since the convention now is to create the reference THEN assign it, this probably won't happen and shouldn't happen.

**Comment by Ross-Esmond** [comment]
But Refs _should_ keep a reference to the object they target.

> Note: this will NOT change how the public api for references work.

I don't believe that's true.

If you create an circle and want to pull the circle out of the scene, **but** want to hold onto the circle object to reinsert it, you would probably use a Ref.

```ts
const circle = createRef<Circle>();
view.add(<Circle ref={circle} />);
circle().remove();

// ...

view.add(circle());
```

You wouldn't expect that Ref to drop the circle at an unspecified time.

WeakRefs, in general, should only be used if their ability to drop the referenced object will go entirely unnoticed, like with a WeakMap or WeakSet. If the object has been garbage collected, then you can't check the WeakMap or WeakSet for that object anyways, so there's no reason for the WeakMap or WeakSet to hold onto the reference, as it cannot affect the program any longer.

**Comment by ccaven** [comment]
Alright, you bring good points. I'll close the issue
