### ISSUE TITLE
How do you render without React?

### ISSUE THREAD

**Issue by NullVoxPopuli** [motion-canvas/motion-canvas#680]
Hello! This looks like a cool project, but I have a confusion:

 - all the examples I found with rendering either had React involved, or hid the detail of how rendering actually happens -- how does rendering work? 
 - The Custom Components page: https://motioncanvas.io/docs/custom-components show something that looks like a Web-component API, likely with some build step, using an old version of decorators? How are they actually rendered though?
 
 Thanks! Totally possible I missed the page that explains this! <3

**Comment by RATIU5** [comment]
What examples are you referring to? I don't believe this library uses React. It does, however, use JSX, which React heavily adopts.

**Comment by aarthificial** [comment]
I can confirm what @RATIU5 said, we do not use React. I'm also curious about what "examples" you are referring to.

Custom components are created by extending our base `Node` class. They have nothing to do with HTML elements.

It seems that you may be confused about the nature of this project. This is not a library for animating HTML on websites. It's an animation tool that renders things using the Canvas API and outputs a video/image sequence.

**Comment by aarthificial** [comment]
Closing due to no response.
