### ISSUE TITLE
Middle mouse button to drag timeline

### ISSUE THREAD

**Issue by PhelixTaken** [motion-canvas/motion-canvas#699]
**Description**
Currently, to go from one point to another in the timeline, I need to use the x-axis scrollbar, which is small (I am using macOS) and error-prone when doing it fast. In an editor like Davinci Resolve, I can just hold the middle mouse button and drag the timeline easily without having to use the scrollbar or to use the left and right holding of the middle mouse button to slowly move the timeline.

**Proposed solution**
This is how it works in Davinci Resolve. Just hold the middle mouse button and move your mouse to the left or right to drag the timeline.

https://github.com/motion-canvas/motion-canvas/assets/42891773/5250db3c-d74a-4781-a64f-9a2d7f7ff975

**Considered alternatives**
I've tried holding left and right middle mouse button but its too slow and I have tried using the scrollbar at the bottom of the page to go left or right but its too small and error-prone (due to it being small).

**Comment by aarthificial** [comment]
Until this is implemented, I'm not sure how you scroll normal websites on macOS, but holding `SHIFT` should turn that action into a vertical scroll, since this is a normal HTML scrollbar. For example, in a mouse with a scroll wheel, holding `SHIFT` will make the wheel scroll the timeline left and right.

**Comment by PhelixTaken** [comment]
Did not know that holding `SHIFT` and then scrolling would horizontally scroll. Thanks for the suggestion :)
