### ISSUE TITLE
Support for normally distributed random values

### ISSUE THREAD

**Issue by ajs1998** [motion-canvas/motion-canvas#704]
**Description**
`useRandom()` provides methods to generate uniformly distributed random values within in a specified range. For statistical visualizations, it is useful to be able to generate normally distributed random values for a given `mean` and `stdev`.

**Proposed solution**
Add and implement a new method to `Random`:
```typescript
normal(mean: number, stdev: number): number;
```

**Considered alternatives**
None

**Additional context**
Similar to Python's `random.gauss()`:
https://docs.python.org/3/library/random.html#random.gauss

**Comment by aarthificial** [comment]
I think calling the method `gauss` would be a bit better.
It would nicely differentiate it from normal vectors which are a common occurrence in other parts of the library.

**Comment by ajs1998** [comment]
Working on this
