### ISSUE TITLE
Create a NullSignal

### ISSUE THREAD

**Issue by gwagner** [motion-canvas/motion-canvas#707]
**Description**
I have a scenario where I am using motion canvas to build out some animated diagrams.  I want the animation flow to be concrete, but I also want to make components of the diagram able to be turned off and on.  I have all of that working, but I am stuck at a point where I need the animation not to pause where I am injecting invisible elements for components that are turned off.  I need a noop signal that will take in the standard signal inputs, but then use a timing and interpolation function that ignores the inputs and keeps on trucking.

Right now, the animation will pause for the duration of invisible elements instead of ignoring them and moving on.  There could be some fancy trickery that takes on understanding the current alpha state of an element and then determines if animation needs to happen based on that alpha state, but that also feels like it is not motion canvas's job to understand those things.  

My goal is to create a component called Fake[Type] and on instantiation setup relevant signals with a NullSignal when an element is supposed to be hidden.

**Proposed solution**
Create a null signal which can be used in place of a normal signal.  The null signal will satisfy the interface of a signal but will not take action on the animation.

**Comment by aarthificial** [comment]
Closing due to no response
