### ISSUE TITLE
Add component for arcs

### ISSUE THREAD

**Issue by juliusv** [motion-canvas/motion-canvas#715]
**Description**
If I understand correctly, the curve objects like https://motioncanvas.io/api/2d/curves/CircleSegment and utility functions like https://motioncanvas.io/api/2d/utils#arc cannot be directly used without wrapping them in custom components or other layers, is that correct? It would be super neat to make some of that functionality available as out-of-the-box components. In my concrete case, I want to draw a partial circle outline / arc (and then optimally also be able to easily map some points onto the arc and move them around, etc.).

**Proposed solution**
Something like an `<Arc />` component with the same properties as https://motioncanvas.io/api/2d/utils#arc.

**Considered alternatives**
I guess an alternative would be for everyone to build their custom arc component, but for me it took a while to figure out that that's even what I'd probably(?) need to do. Some more pointers in the API docs for how to use the curves / utils helper functions could go a long way as well.

**Comment by juliusv** [comment]
Ah yes, that sounds like a good idea!

And thank you, now that I took an even closer look at `Circle`, it's actually the first time that I noticed that it supports drawing arcs as well (without arrows etc., but good enough for me) :)

**Comment by aarthificial** [comment]
Closed by #771
