### ISSUE TITLE
Animation Flow documentation , Flicker function, Import.

### ISSUE THREAD

**Issue by SlipinF** [motion-canvas/motion-canvas#751]
In the Animation Flow documentation under flicker function section the provided code snippet uses :

`import {ThreadGenerator} from '@motion-canvas/core';  `to import ThreadGenerator, this results in the following error :

`Module '"@motion-canvas/core"' has no exported member 'ThreadGenerator'.ts(2305)`

the correct  import snippet is : 

`import {ThreadGenerator} from '@motion-canvas/core/lib/threading';`

**Comment by aarthificial** [comment]
Closing due to no response
