### ISSUE TITLE
pre-render presentation

### ISSUE THREAD

**Issue by Walle123** [motion-canvas/motion-canvas#752]
So i am having this problem that my presentation got quiet big and thus will **stutter** when presenting.
I believe there must be a way in which the presentation can be pre-rendered which will greatly improve performance on presenting.

**Comment by aarthificial** [comment]
In general, the length of the animation shouldn't influence the playback performance. It can make seeking/switching slides take longer, but it shouldn't cause drops in framerate.

Can you provide more information on what causes the stutter?
1. Does the editor also struggle to play your animation or does the problem only occur when presenting?
2. How long is your animation and how many scenes do you have?
3. Is there something performance specific you do?
  Maybe you're using thousands of elements, or doing some expensive calculations each frame?

**Comment by Walle123** [comment]
Hi, thanks for the quick reply.

1. It also struggles in the editor and rendering takes more time on those frames as well.
2. My animation is 47 seconds long and everything happens in just one scene.
3. The part it most struggles to display is when i zoom into stuff like the clip i attached.
My editor somehow already sits at 47-48 when i put it to 60 fps ( always the case ) and when the stutter begins it drops to about 20.
On the laptop, on which i plan to present, the fps go from 35 to 15 which increases the animation time.

https://github.com/motion-canvas/motion-canvas/assets/80287602/609500bb-956a-48ea-933e-4d570b3aa852

**Comment by Walle123** [comment]
Addition to my previous comment.

When i increase the fps in the UI to about 70 it will run my animation on my computer (windows 11) now  on smooth 70 with out stutter.
On my laptop (ubuntu) i had to switch from firefox to the edge browser to run it smooth.

**Comment by aarthificial** [comment]
Interesting. There's a known issue with the animation loop dropping frames when the monitor's refresh rate is different than 60Hz
Can you check if that's the case with your PC's monitor? Seems like it may have 75Hz

**Comment by Walle123** [comment]
My monitors refresh rate is 144Hz.
