### ISSUE TITLE
CodeBlock Selection Docs Overhaul

### ISSUE THREAD

**Issue by hhenrichsen** [motion-canvas/motion-canvas#766]
**Description**
The [selection](https://motioncanvas.io/docs/code-block#selection) portion of the CodeBlock docs has some examples that don't compile, and starts with a raw selection and only shows the helpers after. I think the former should be fixed, and the latter flipped to prioritize showing the helpers.

**Comment by WaldemarLehner** [comment]
I can work on this :smiley:

**Comment by WaldemarLehner** [comment]
Just fyi. I am currency moving out so I am a bit occupied with that.  I expect to pick this up again in like a week if all things go well
