### ISSUE TITLE
Time events are ignored in rendering if they are named only with numbers.

### ISSUE THREAD

**Issue by aleqsio** [motion-canvas/motion-canvas#769]
**Describe the bug**
If I name some events 0, 1, 2, they are respected in preview but skipped in ffmepg or png sequence rendering. Probably my fault, but I'd add a cast to string since it breaks in such unexpected ways and throws no TS warning.

**To Reproduce**
Events like this work fine in rendering
```typescript
{
      "name": "a0",
      "targetTime": 9.670532582110415
},
``` 
   
but ones like this (created by `waitUntil(5)`) are just played one after the other

```typescript
{
      "name": 0,
      "targetTime": 9.670532582110415
},
``` 

**Expected behavior**
The events should be respected during rendering

**Console errors**

**Package versions:**
*Click on the version in the bottom right corner to copy the versions*

- core: 3.9.0
- two: 3.9.0
- ui: 3.9.0
- vitePlugin: 3.9.0

**Additional context**

**Comment by aarthificial** [comment]
> throws no TS warning.

It does. `waitUntil` expects the first parameter to be of type `string`:
![image](https://github.com/motion-canvas/motion-canvas/assets/64662184/ea0f2560-ecab-4bc1-916b-afe07c97d914)

Verifying if the provided parameter has a correct type may seem like a trivial change in this specific example but if we were to be consistent about this we'd need to add a ton of checks everywhere to make sure that people don't provide invalid arguments to any functions. But that's the whole point of using TypeScript.
