### ISSUE TITLE
Motion Canvas doesn't export video after setting its export mode to FFmpeg.

### ISSUE THREAD

**Issue by MubinMuhammad** [motion-canvas/motion-canvas#781]
This is the code for my `vite.config.ts` file:

```ts
import {defineConfig} from 'vite';
import motionCanvas from '@motion-canvas/vite-plugin';
import ffmpeg from '@motion-canvas/ffmpeg';

export default defineConfig({
  plugins: [
    motionCanvas(),
    ffmpeg(),
  ],
});
```

And after I click on the render button in the localhost server of motion canvas. It renders it fine. But I get a lot of images of type .png in the `output/project` directory. What is the reason for it?

By the way, I did select the `Video (FFmpeg)` option in the list of available exporters while creating the project.

Thanks.

**Comment by aarthificial** [comment]
After setting up an exporter, it should appear in the video settings:
![image](https://github.com/motion-canvas/motion-canvas/assets/64662184/3ffaa7b2-5f65-429e-8b58-df4e82242462)

Can you confirm that you selected `Video (FFmpeg)` there?

**Comment by MubinMuhammad** [comment]
Thanks, I didn't check the rendering tab.  It does show the `Video (FFmpeg)` option in the tab list.
