### ISSUE TITLE
Add stroke prefix to stroke related properties

### ISSUE THREAD

**Issue by sinnom** [motion-canvas/motion-canvas#785]
**Description**
Rename [`Shape`](https://motioncanvas.io/api/2d/components/Shape/)'s stroke related properties to "stroke___" (i.e., `lineCap` becomes `strokeLineCap`). 

**Benefits**
- It would become easier to identify stroke related properties. 
- Reduces ambiguity between the [`lineHeight`](https://motioncanvas.io/api/2d/components/Shape/#lineHeight) and [`lineWidth`](https://motioncanvas.io/api/2d/components/Shape/#lineWidth) properties.
- Aligns more closely with the SVG attribute names of the same kind. https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linecap

If this would be desired for the project I'd be happy to implement the change.

**Comment by sinnom** [comment]
Ah apologies for assigning you, I'm new to github issues.

**Comment by aarthificial** [comment]
No worries, the template is configured to assign me on purpose.

The way I see it, Motion Canvas is a Canvas library - not an SVG library.
This is why all property names in the Shape node map one-to-one to the Canvas API.
I don't see why we should align with the SVG spec as the library has nothing to do with it.

On top of that, changing the names of public properties would be annoying to people as it would break all existing projects.
