### ISSUE TITLE
Add API Documentation

### ISSUE THREAD

**Issue by sinnom** [motion-canvas/motion-canvas#789]
**Description**
Much of the API is undocumented. Doc comments on methods/properties, with links to relevant guides, would be helpful for folks learning how to use Motion Canvas.

I'd be happy to start working on this.

**Comment by sinnom** [comment]
Sorry, I meant to ask: would this be welcome for the project? Waiting to start working on it until I have the go-ahead.

**Comment by aarthificial** [comment]
This is kind of implied in our contribution guide:
> If you intend to change the public API, make any non-trivial changes to the implementation, or create brand-new guides in the documentation, make sure to [create an issue](https://github.com/motion-canvas/motion-canvas/issues/new?template=feature_request.md) first.

If you want to improve the existing documentation or add missing TSDocs to classes, you don't need to create an issue for this, feel free to open a PR directly.
