### ISSUE TITLE
Dragging MetaFieldView Input

### ISSUE THREAD

**Issue by fangjunzhou** [motion-canvas/motion-canvas#799]
**Description**
The current input field only supports typing the value. For numerical fields like number fields and vector fields, it'll be more intuitive to support dragging behavior.

![Peek 2023-08-23 17-05](https://github.com/motion-canvas/motion-canvas/assets/79500078/b6b8614e-396c-4484-8ba9-725a1729267c)

**Proposed solution**
Left-click and drag to change the value. Single left-click to edit the value manually.

![Peek 2023-08-23 17-13](https://github.com/motion-canvas/motion-canvas/assets/79500078/e4391d73-92d4-42ba-a4c6-8536a47102b5)

**Considered alternatives**
Blender solution to the dragging numerical field: https://docs.blender.org/manual/en/latest/interface/controls/buttons/fields.html

**Comment by aarthificial** [comment]
It's worth considering if the [Pointer Lock API](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API) could used while dragging to prevent unnecessary mouse movement.

**Comment by luv2027** [comment]
is anyone working on the issue i want to work on this issue please!!

**Comment by fangjunzhou** [comment]
> is anyone working on the issue i want to work on this issue please!!

I'm sorry I'm not working on this issue recently. You can claim it!

**Comment by TungVietLe** [comment]
[luv2027](https://github.com/luv2027) are you still working on the issue I wonder? I want to tackle the issue please.

**Comment by jmaen** [comment]
Is anybody currently working on this?

**Comment by TungVietLe** [comment]
No, feel free to work on it please

**Comment by jmaen** [comment]
Alright, I'll take a look at it!
