### ISSUE TITLE
Hovering and dragging time events should display vertical line when such event happens

### ISSUE THREAD

**Issue by jakweg** [motion-canvas/motion-canvas#804]
**Description**
When you drag time event there is a vertical line below your cursor. It's useful when synchronizing events with voice, but in my opinion this line should display "at the start" of time event rather then "where I clicked the tag".
This is how it's now:
![image](https://github.com/motion-canvas/motion-canvas/assets/20194971/e3b86686-249d-47e9-939c-f5f133454cc4)

This fix will make it clear where time events start and allow for easier and more precise adjustments.

**Proposed solution**
Where the line should be (red):
![image](https://github.com/motion-canvas/motion-canvas/assets/20194971/e9a197ea-0b7b-464c-835d-2caf9e4a65e9)

**Comment by alsongarbuja** [comment]
@jakweg do you mean a new red line should appear when hovering over the `LabelClip` element or should the white line appear infront of the `LabelClip` when hovering over it.

I am relatively new to motion canvas and wanted to work in this issue.

**Comment by jakweg** [comment]
White line should appear in front of the LabelClip when hovering over it.
Red line is only added here by me to illustrate where the white one should be.

**Comment by alsongarbuja** [comment]
Got it I will try to work on this issue
