### ISSUE TITLE
Allow code edit/remove to work with string interpolation.

### ISSUE THREAD

**Issue by gk-patel** [motion-canvas/motion-canvas#809]
**Description**
I want to be able to use variables when editing code in CodeBlock 

Say, I have three varaibles, 

```
const codeStart = "..."; 
const codeToBeReplaced = "..."; 
const codeEnd = "..." 
```
Initally the code block will contain "codeStart + codeToBeReplaced + codeEnd"

I want the following animation to work: 

```
yield * codeRef().edit(1, false)`${codeStart }${edit(codeToBeReplaced , "new code" )}${codeEnd}`
```

For this I get the following error: 

`Cannot read properties of undefined (reading 'spans')`

**Proposed solution**
None

**Considered alternatives**
currently need to have full text as string. Following what is in the documentation works, but creates huge files with lot of copy-paste.

**Comment by aarthificial** [comment]
Can you provide a simple scene that reproduces this issue?
This seems to be working as expected:
```tsx
import {makeScene2D} from '@motion-canvas/2d';
import {CodeBlock, edit} from '@motion-canvas/2d/lib/components/CodeBlock';
import {waitFor, createRef} from '@motion-canvas/core';

export default makeScene2D(function* (view) {
  const codeRef = createRef<CodeBlock>();

  const codeStart = 'const ';
  const codeToBeReplaced = 'a';
  const codeEnd = ' = value;';

  yield view.add(
    <CodeBlock ref={codeRef}>
      {codeStart + codeToBeReplaced + codeEnd}
    </CodeBlock>,
  );

  yield* codeRef().edit(1, false)`${codeStart}${edit(codeToBeReplaced, 'new code')}${codeEnd}`;

  yield* waitFor(5);
});
```

**Comment by gk-patel** [comment]
Thank you @aarthificial - it does work as you showed above !!!
In my case, I am trying to get the current code from `codeRef().code()` and do an in-line replacement. 
The problem is, `codeRef().code()` give some kind a dictionary `{language:.., spans:..., }` 
I was assuming it would be string, this is where I got confused.

**Comment by aarthificial** [comment]
@gk-patel 
Unfortuantely, there's no built-in way to extract the current code as a string, but you can do that manually using `code-fns` (the package used by the current `CodeBlock` implementation):
```ts
import {parse, toString} from 'code-fns';

// ...

const codeText = toString(parse(codeRef().code()));
```

Also, I suggest you take a look at [the New Code Node proposal](https://github.com/orgs/motion-canvas/discussions/688) and leave any ideas for improvements you have over there because the old `CodeBlock` most likely won't be developed any further.
