### ISSUE TITLE
Feature | Media control buttons for "go to start" and "go to end"

### ISSUE THREAD

**Issue by me-nkr** [motion-canvas/motion-canvas#812]
**Description**
Media control buttons for "go to start" and "go to end".

**Proposed solution**
We could use these buttons⏮and⏭respectively for start and end. These buttons could be shown in the media control area, directly visible or semi-hidden to not mess up the current UI.

**Considered alternatives**
- We can use the timeline to do this as of now, but it requires us to scroll the timeline from where it is right now
- > You can use SHIFT + ArrowLeft and SHIFT + ArrowRight to go to the start and end respectively
  - The above is great but a UI control is necessary I believe, for those times we just keep mouse in one hand and a mug of coffee in the other 😅

**Comment by hhenrichsen** [comment]
Adding `c-accepted` based on [this comment](https://github.com/orgs/motion-canvas/discussions/811#discussioncomment-7224405).
