### ISSUE TITLE
Why do some emojis come up and others dont ? 

### ISSUE THREAD

**Issue by gk-patel** [motion-canvas/motion-canvas#815]
**Describe the bug**
If I give a string with emoji in the vs-code, 
<img width="175" alt="image" src="https://github.com/motion-canvas/motion-canvas/assets/42677721/aee7d270-d6a7-490c-ac7b-068f20bb1743">
(as text: # This is an emoji ❤️ 😊 😀)

They are not rendered properly
<img width="228" alt="image" src="https://github.com/motion-canvas/motion-canvas/assets/42677721/2dacd8d4-576b-4121-bf47-d6a8b0cbd96b">

**Additional context**
I checked your code, you are using fillText as specified here 
https://stackoverflow.com/questions/56312457/how-to-load-and-draw-emojis-on-canvas-efficiently 
Thought it would work, not sure why it does not.

**Comment by aarthificial** [comment]
Right now, `CodeBlock` uses a naive approach to splitting strings into individual characters which doesn't take into consideration UTF-8 characters bigger than 8 bits (emojis, CJK characters, etc.)
You can see in the image you provided that the two last emojis are split into four invalid characters.

Sadly, we'll most likely not fix this for the old `CodeBlock` node.
We have a new `Code` node proposal (#688) which will not have these issues but it's still in the works.

**Comment by gk-patel** [comment]
Thank you, I am looking forward to the new module.
