### ISSUE TITLE
npm init -- "no prompting" not working

### ISSUE THREAD

**Issue by jryebread** [motion-canvas/motion-canvas#816]
Posted in the discord about how `npm init @motion-canvas@latest --yes -- --name Hello --path . --language ts` still prompts the user for text input. 

I'm trying to create an automated script that sets up motion canvas in a web container.

not sure why this isn't working: https://github.com/motion-canvas/motion-canvas/pull/668
![image](https://github.com/motion-canvas/motion-canvas/assets/22125118/ffc1cba8-0008-4dc5-92f8-d4ac5f7e95c5)

**Comment by aarthificial** [comment]
Pasting my response from Discord for prosperity:

---
Funny story, `name` needs to be a valid npm package name and those can't contain uppercase letters
If you do
```sh
npm init @motion-canvas@latest -- --name hello --path ./hello --language ts --plugins core
```
Everything works just fine
*(Note the `hello` instead of `Hello`)*
