### ISSUE TITLE
Cannot give Parent Node attributes to Child Node

### ISSUE THREAD

**Issue by GondorCallsForAid** [motion-canvas/motion-canvas#827]
My goal was to tie the color of the polygon-parent node to the color of the rect-child node, 
so that I can later animate both colors by just calling the polygon-node reference tMain.

But when I try setting the color of the child using the polygon-node reference: ```  fill={tMain().fill} ```
I get the error:
```Cannot read properties of undefined (reading "fill")```

The issue might also likely be me being very new to typescript, but I would be happy for any suggestions.

```ts
const t =
<>	
  <Polygon
    ref={tMain}
    sides={8}
    y={-100}
    size={120}
    fill={'grey'}
    opacity={0}
  >
    <Rect
      ref={tBot}
      y={28+100}
      width={111}
      height={100}
      fill={tMain().fill}
      opacity={tMain().opacity}
    >
  </Polygon>
</>

```

**Comment by aarthificial** [comment]
You can read about how Motion Canvas uses JSX in [this section of our docs](https://motioncanvas.io/docs/hierarchy) but in general, your snippet is equivalent to something like this:
```ts
const t = [
  new Polygon({
    ref: tMain,
    // ...
    children: [
      new Rect({
        // ...
        fill: tMain().fill,
        // ...
      }),
    ],
  }),
];
```
Notice that for a new `Polygon` to be constructed, its children need to be constructed first, so when `fill: tMain().fill` is resolved, the polygon doesn't exists yet and so the `tMain` reference has not been assigned yet.

A really easy solution would be to just use a signal which is lazy and so it won't be called immediately:
```ts
const t =
<>	
  <Polygon
    ref={tMain}
    sides={8}
    y={-100}
    size={120}
    fill={'grey'}
    opacity={0}
  >
    <Rect
      ref={tBot}
      y={28+100}
      width={111}
      height={100}
      fill={() => tMain().fill}
      opacity={() => tMain().opacity}
    >
  </Polygon>
</>
```

**Comment by GondorCallsForAid** [comment]
Thank a lot, that resolved my issue :D
