### ISSUE TITLE
Can you assign a reference to an already created shape?

### ISSUE THREAD

**Issue by sancarn** [motion-canvas/motion-canvas#828]
Not a bug, but a question... I'd like to be able to do something like this in effect:

```ts
type RefEx<T> = {
  view: T;
  current: () => T;
};

function createRefEx<T>(component: T): RefEx<T> {
  const ref = createRef<T>();
  const elementWithRef = component.bindRef(ref);          //<--- **THIS**
  return {
    view: elementWithRef,
    current: () => ref(),
  };
}
```

Such that I can create objects like this:

```ts
const myCircle = createRefEx<Circle>(
  <Circle
     x={-300}
     width={140}
     height={140}
     fill="#e13238"
  />
);
view.add(myCircle.view)
yield* myCircle.current().position.x(300,1).to(-300,.1)
```

Was wondering if anything like this is possible? I did do a brief search of the component structure but couldn't see anything specifically to indicate that one could bind a ref to an existing component...

**Comment by sancarn** [comment]
Oh my lord... didn't realise you could just create elements and add them to the view like this...

```ts
  const circle = <Circle x={-300} width={140} height={140} fill="#e13238" />;
  view.add(circle);

  // we can now animate our circle:
  yield* circle.scale(2, 0.3);
```

**Comment by sancarn** [comment]
Turns out I could actually benefit from this, because there are some scenarios where `ref` is required it seems...

**Comment by sancarn** [comment]
Found there is indeed a `clone` function

```ts
export type RefEx<T extends Node> {
    node: Node,
    current: ()=>T
}
export function createRefEx<T extends Node>(node: T): RefEx<T>{
    let ref = createRef<T>();
    let element = node.clone({ref})
    return {
        current: ref,
        node: element
    }
}
```

**Comment by aarthificial** [comment]
Also, your code won't work because nodes ignore the `ref` property, it's used exclusively by the jsx runtime:
https://github.com/motion-canvas/motion-canvas/blob/20cceef8525e809bff9706fcd7082d7e103a085b/packages/2d/src/jsx-runtime.ts#L37-L39

If you want to manually set the value of a reference you can simply do this:
```ts
const myRef = createRef<Txt>();
myRef((<Txt />) as Txt);
```

**Comment by sancarn** [comment]
> > because there are some scenarios where ref is required it seems...
> 
> Can you elaborate on this? References should be completely optional. 

Sure! 

```ts
  const x = <Img />;
  x.size()
```
returns a type error because `<Img />` returns a node instance rather than an `Img` instance (I think?)

![image](https://github.com/motion-canvas/motion-canvas/assets/7938900/7a37d3f1-db3b-4699-92c1-843fdcf3bac4)

However using a reference you do get intellisense and no type errors.

> If you want to manually set the value of a reference you can simply do this:

Thanks! :)

**Comment by aarthificial** [comment]
JSX tags return the correct instance it's simply typed as the base `Node` class.
That's a [TypeScript limitation](https://www.typescriptlang.org/docs/handbook/jsx.html#the-jsx-result-type):
> However, it is not possible to retrieve type information about the element, attributes or children of the JSX from this interface. It is a black box.

But you can easily cast them to the correct type like this:
```tsx
const x = <Img /> as Img;
```

**Comment by sancarn** [comment]
> > However, it is not possible to retrieve type information about the element, attributes or children of the JSX from this interface. It is a black box.

Ahh gotcha, thanks! Very useful to know!
