### ISSUE TITLE
Opacity should be at max 1 (or error when higher values are provided)

### ISSUE THREAD

**Issue by sancarn** [motion-canvas/motion-canvas#830]
**Describe the bug**
I created some animation like this:

```ts
const spreadsheets = [1, 2, 3].map(
    (e) =>
      new Wrapper(
        view,
        <Img x={2000} y={0} width={600} opacity={100} src={fileSpreadSheet} />
      )
  );
```

Not realising that opacity should sit between `0` and `1`, which led to a strange unexpected behaviour when setting opacity to 0 on all images i.e.

```ts
yield* all(...spreadsheets.map(e=>e.node.opacity(0,0.5)));
```

Led to this "unexpected" behaviour:

https://youtu.be/D4NVWU0kXdI

I.E. 1 starts fading, while the other 2 remain at full opacity:

![image](https://github.com/motion-canvas/motion-canvas/assets/7938900/9779edc7-eb18-4764-8af1-c8a5ecdf104c)

Changing:

```ts
<Img x={2000} y={0} width={600} opacity={100} src={fileSpreadSheet} />
```

To:

```ts
<Img x={2000} y={0} width={600} opacity={1} src={fileSpreadSheet} />
```

Fixes the animation issue.

**Expected behavior**

Opacity should either:

* Be capped at 1 with a warning
* Should throw an error indicating to the user that it should be between 0 and 1.

I think a warning would suffice.

**Package versions:**
- core: 3.11.0
- two: 3.11.0
- ui: 3.11.0
- vitePlugin: 3.11.0

**Comment by aarthificial** [comment]
I agree that the value should be clamped, but I don't think we should add a warning.
It would be annoying to people who want to purposefully use the fact that opacity is clamped and would force them to manually invoke `clamp` each time they set the opacity.

To avoid confusion, we could add the missing documentation to the `opacity` property, specifying that the range goes from 0 to 1.

**Comment by rmhartog** [comment]
Looks like an easy and helpful fix, I'd like to pick this one up.
