### ISSUE TITLE
Add Vector constants for all origins

### ISSUE THREAD

**Issue by aarthificial** [motion-canvas/motion-canvas#844]
**Description**
The [`Vector2`](https://github.com/motion-canvas/motion-canvas/blob/main/packages/core/src/types/Vector.ts) class should be extended by new static properties with vectors representing all [`Origin`s](https://github.com/motion-canvas/motion-canvas/blob/main/packages/core/src/types/Origin.ts).

For example:
```ts
public static readonly top = new Vector2(0, -1);
```
The value of each constant should be equal to the vector returned by `Vector2.fromOrigin` for the given origin:
```ts
Vector2.fromOrigin(Origin.Top); // Vector2(0, -1)
```

**Comment by CactusPuppy** [comment]
I am beginning work on this issue.
