### ISSUE TITLE
Directly select timeline range

### ISSUE THREAD

**Issue by jmaen** [motion-canvas/motion-canvas#875]
**Description**
Since the timeline scrubbing PR #862 it's possible to move the selected range and edit it using the two handles while pressing `SHIFT`. 
I think it would be nice to be able do directly select the range (start handle is positioned on `mousedown` and end handle on `mouseup`). That would be especially useful when zoomed in on a specific part in the timeline, as then the rangle handles will often times be off-screen.

**Proposed solution**
Using another key, e.g. `ALT` or any other key combination (maybe using `RMB` might work as well?), that will allow to edit the range by directly "drawing it in". I suppose most of the (dragging) logic should already be there in the `RangeSelector.tsx`.

I'd imagine something like this:

![range selection](https://github.com/motion-canvas/motion-canvas/assets/47495425/81cb1eef-8b31-4ae2-879d-5806ff917c4b)

**Comment by aarthificial** [comment]
Can you tell me what software is the recording from and how it works over there? (What button needs to be held, etc.)

Also, since we're at it, we should probably add shortcuts for setting the start/end of the range to the current playhead position.
For example, in After Effects it's done using the `B` and `N` keys.

**Comment by jmaen** [comment]
The software in the clip is actually FL Studio (a Digital Audio Workstation), so it has nothing to do with video editing / animation. It was just the first thing that came to mind.
In FL Studio, left click and dragging moves the playhead, and right click and dragging selects the range. 

The shortcuts sound nice as well!

**Comment by aarthificial** [comment]
Alright, I'd go for holding shift + right mouse drag then

**Comment by jmaen** [comment]
Alright, I think that would've been my preferred option as well! I'll look into it over the holidays. You can assign it to me if you want to

**Comment by jmaen** [comment]
Unfortunately it seems like we need to find a different solution.
When `SHIFT` is pressed, Firefox apparently forces the context menu to open, even when preventing default behavior on `contextmenu`.
On Chrome that isn't a problem.

**Comment by aarthificial** [comment]
That's a bummer. How about `CTRL` + `SHIFT` + `LMB` then?

**Comment by jmaen** [comment]
I think `CTRL` + `SHIFT` should work fine!
