### ISSUE TITLE
Motion Canvas Controls Disappeared

### ISSUE THREAD

**Issue by CleverFlare** [motion-canvas/motion-canvas#926]
**Describe the bug**
I'm new to Motion Canvas, so I'm trying to create a very basic animation like the one in the docs. When the scenes update the whole Motion Canvas editor disappears, only the background color is present.
Even if I terminate the server and run it again the problem persists.

**To Reproduce**
1. use the command `npm init @motion-canvas@latest`
1. choose all the default configurations
1. `cd` to the folder where the project lives
1. run `npm install`
1. run `npm start`
1. make a change to the `example.tsx` file, just copy and paste the example code in the Quickstart page in the docs
1. now the `http://localhost:9000/` is a blank page with only the background color

```ts
export default makeScene2D(function* (view) {
    const myCircle = createRef<Circle>();

    view.add(
      <Circle
        ref={myCircle}
        // try changing these properties:
        x={-300}
        width={140}
        height={140}
        fill="#e13238"
      />,
    );
  
    yield* all(
      myCircle().position.x(300, 1).to(-300, 1),
      myCircle().fill("#e6a700", 1).to("#e13238", 1),
    );
});
```

**Expected behavior**
The `http://localhost:9000/` should reflect the change and also show the editor. 

**Console errors**
```
Uncaught TypeError: class heritage ObjectMetaField is not an object or null
    <anonymous> http://localhost:9000/node_modules/.vite/deps/chunk-QQZII4ON.js?v=8a2893be:4948
```

**Package versions:**

- core: 3.13.0
- ui: 3.13.0

**Additional context**
I see this warning in the console which I don't know whether or not is relevant:
```
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content.
```

**Comment by aarthificial** [comment]
Can you try doing the following:
1. Stop the editor (by pressing `CTRL + C` in the terminal where you run `npm start`)
2. Delete the following directory from your project: `node_modules/.vite`
3. Restart the editor (by running `npm start` again)

Let me know if this helps.

**Comment by CleverFlare** [comment]
@aarthificial 
It did solve the issue. Thanks a lot! ✨
