### ISSUE TITLE
Editor locks up when setting the FPS to a negative value

### ISSUE THREAD

**Issue by SecondFlight** [motion-canvas/motion-canvas#936]
**Describe the bug**
Setting the preview FPS to a negative value causes the editor to lock up.

**To reproduce**
1. Create a new project
2. Open the editor
3. Set the preview FPS to a negative value

**Expected behavior**
The editor should correct or ignore the user's setting, but should not lock up.

**Package versions:**
- core: 3.14.0
- two: 3.14.0
- ui: 3.14.0
- vitePlugin: 3.14.0

**Additional context:**
Thanks for creating this project! I'm a first-time user and was exploring the UI. The preview FPS input can be changed with click & drag, and while changing it I accidentally set it to -6, causing the editor to lock up.

For anyone else with this issue, it can be fixed by editing `src/project.meta` and changing `'preview' -> 'fps'` to a positive number.

**Comment by aarthificial** [comment]
Thanks for the report!
It will be fixed in `3.14.1`
