### ISSUE TITLE
Introduce Signal Effects

### ISSUE THREAD

**Issue by aarthificial** [motion-canvas/motion-canvas#945]
**Description**
The value of a signal is calculated only when something requests it by invoking it.
This works great with the current architecture because, during rendering, all signals necessary to display the animation will be invoked and therefore updated. It also automatically skips expensive calculations like matrix propagation (calculating the global matrix of a node) unless something actually needs it.

This approach, however, makes it impossible to "observe" for changes in signals. To do that, one would need to write a loop that accesses the signal in each frame. There should be a built-in, simpler way to achieve this.

**Proposed solution**
Most UI libraries have a concept of `effect` that does exactly this. While their signal implementation is usually different than ours (relying on registration rather than laziness), we should be able to replicate a familiar API.
This is when signals in MC are computed:
```ts
const radius = createSignal(1);
const area = createSignal(() => {
  console.log('area recalculated!');
  return Math.PI * radius() * radius();
});

area(); // area recalculated!
area();
radius(2);
area(); // area recalculated!
radius(3);
radius(4);
area(); // area recalculated!
```
And here's how the `createEffect` function would work:
```ts
const radius = createSignal(1);
createEffect(() => {
  // watch for changes to radius
  radius();
  console.log('area recalculated!');
}); // area recalculated!

radius(2); // area recalculated!
radius(3); // area recalculated!
radius(4); // area recalculated!
```
Additionally it would be useful to have a variant of effect that is deferred until the end of the frame:
```ts
const radius = createSignal(1);
createDeferredEffect(() => {
  // watch for changes to radius
  radius();
  console.log('area recalculated!');
}); // area recalculated!

radius(2);
radius(3); 
yield; // area recalculated!
radius(4);
yield; // area recalculated!
```

**Comment by mancopp** [comment]
Hi, I would like to claim this issue
