### ISSUE TITLE
Error while using "npm start" using termux

### ISSUE THREAD

**Issue by Lufims** [motion-canvas/motion-canvas#949]
**Describe the bug**
I'm trying to use motion canvas on termux, and when I use the npm start command it says this error

**To Reproduce**
Try to use motion canvas with termux following the quick start guide

```ts
export default makeScene2D(function* (view) {
  // troublesome code
});
```

**Expected behavior**
Start the editor

**Console errors**
![Screenshot_20240209_141846_Termux](https://github.com/motion-canvas/motion-canvas/assets/73536178/06b26c2e-cf08-4a45-bda5-aad4199132a7)

**Package versions:**

I don't know

- core: [e.g. 1.0.0]
- ui: [e.g. 1.0.0]

**Additional context**

**Comment by aarthificial** [comment]
Can you check your node version by running:
```bash
node -v
```
to make sure it's version 16 or greater?

**Comment by Lufims** [comment]
> Can you check your node version by running:
> 
> ```shell
> node -v
> ```
> 
> to make sure it's version 16 or greater?

It's 20.2.0
![Screenshot_20240215_090657_Termux](https://github.com/motion-canvas/motion-canvas/assets/73536178/82a771b8-2649-49c1-bb1a-aba5135f96ee)

**Comment by aarthificial** [comment]
Could you also try to scaffold an empty vite project to see if that alone works?
https://vitejs.dev/guide/#scaffolding-your-first-vite-project
It looks like the error is thrown on their side and not in our files.

Also, before you put any more effort I'd recommend checking the online version of the editor first:
https://motioncanvas.io/editor/quickstart/
Because it was not developed with phones in mind and may not work with touch gestures.

**Comment by Lufims** [comment]
> Could you also try to scaffold an empty vite project to see if that alone works? https://vitejs.dev/guide/#scaffolding-your-first-vite-project It looks like the error is thrown on their side and not in our files.
> 
> Also, before you put any more effort I'd recommend checking the online version of the editor first: https://motioncanvas.io/editor/quickstart/ Because it was not developed with phones in mind and may not work with touch gestures.

It worked
![Screenshot_20240215_093240_Termux](https://github.com/motion-canvas/motion-canvas/assets/73536178/89c078c4-7835-49a3-8488-3a688bf9a7a8)
![Screenshot_20240215_093346_Chrome](https://github.com/motion-canvas/motion-canvas/assets/73536178/557b1eed-44c2-45b9-8ae5-76cd82fcaa00)

**Comment by aarthificial** [comment]
Not sure what's the problem then. It may be caused by the CJS build of Vite. They deprecated it in version 5 and no longer use it which could explain why `v5.1.2` works.
We will be switching to the ES version in #923 but that's still some time away sadly.

**Comment by Lufims** [comment]
> Not sure what's the problem then. It may be caused by the CJS build of Vite. They deprecated it in version 5 and no longer use it which could explain why `v5.1.2` works. We will be switching to the ES version in #923 but that's still some time away sadly.

I see, I will wait then, because I tried it on termux just for fun.
