### ISSUE TITLE
Seperate Inherited properties/functions from other inherited properies/functions

### ISSUE THREAD

**Issue by JPAKx4** [motion-canvas/motion-canvas#958]
In lots of documentation I am used to, the properties/functions that are unique to a class are the only ones shown or are in separated sections. 

Ex: 
- https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html
- https://docs.godotengine.org/en/stable/classes/class_button.html
- https://docs.unity3d.com/ScriptReference/UIElements.Button.html

A simple "Inherited Members" section on each doc would greatly improve the readability of a doc. When extending a class, it is important to know which functions that you actually need and what makes sense for your structure.

For example, I was looking to see if Path had a property for changing arrow shape. I had to look through the members, go to the curve page, look through there, and finally saw that there was a issue posted about this. If the curve/path had less members, this process would have been much quicker.

Thank you for the cool editor guys :)

**Comment by aarthificial** [comment]
Hi, thanks for the report!
You can already filter out inherited and/or protected properties using the `Filter` dropdown at the top of the page:
![image](https://github.com/motion-canvas/motion-canvas/assets/64662184/e9ee3e3a-8865-41f8-9994-a6d0ef5485fc)

**Comment by JPAKx4** [comment]
Dang, I'm stupid lol
