### ISSUE TITLE
Add a length() accessor to the Line component

### ISSUE THREAD

**Issue by zweek** [motion-canvas/motion-canvas#963]
**Description**
For my own use of MC i often have compositions where I have a simple line with a label next to it denoting the length of that line. Currently I always have to calculate that length manually (or write my own length function that I then have to import into every scene)

**Proposed solution**
For lines with exactly 2 points, I imagine it would be a fairly shrimple implementation of pythagoras. For lines with >2 points, you could iterate through all the points and calculate the length of each segment and add them all up. This would probably get really complicated if you wanted to account for points rounded off with `radius`, but I don't know important it would be to calculate that accurately. (at least for my own use case I wouldn't even need to go above 2 points in the first place)

**Comment by aarthificial** [comment]
Any node that extends `Curve` (`Line`, `Circle`, `Spline`, etc) has a method called [`arcLength()`](https://motioncanvas.io/api/2d/components/Curve#arcLength) that should be exactly what you need. It returns the length of the entire curve accounting for the radius etc.
