### ISSUE TITLE
Different Browsers, Same Code, Different Appearance.

### ISSUE THREAD

**Issue by Lil-Timmy** [motion-canvas/motion-canvas#966]
**Describe the bug**
So when I use my default browser being Firefox, and use the conic gradient type I get a gradient that I'd expect but with weirdly about half opacity, while on Chrome I get an expected but still slightly different look to the gradient but it's proper and fully opaque.

**To Reproduce**
The following code in a new project in Chrome should be expected and on Firefox and potentially other browsers vary quite a bit.

```ts
import { Circle, Gradient, Layout, Node, Rect, makeScene2D, } from '@motion-canvas/2d';
import { Color, Vector2, all, createRef, linear, loop, waitFor, } from '@motion-canvas/core';
import { Colors, } from '../@timmy/Colors';

export default makeScene2D(function* (view) {

  const colorWheel = createRef<Circle>();
  const gradient = new Gradient({
    type: 'conic',
    
    stops: [
      {offset: 0, color: "#00ff00ff"}, // Green
      {offset: 0.333, color: "#ff0000ff"}, // Red
      {offset: 0.666, color: "#0000ffff"}, // Blue
      {offset: 1, color: "#00ff00ff"}, // Green
    ],
  });
  

  view.fill(Colors.darkGray);

  view.add(
    <Circle
      ref={colorWheel}
      size={1000}
      fill={"#ffffff"}
      //filters={}
      >
      <Circle
        size={1000}
        fill={gradient}
      >

      </Circle>
    </Circle>
  )

  yield* colorWheel().rotation(360, 2, linear);
})
```

**Console errors**
None in the Motion-Canvas console, one error possibly applicable in the log for firefox: 
![image](https://github.com/motion-canvas/motion-canvas/assets/65428672/5e82c33d-ac99-434a-8e9a-2aa26b4d0dda)

**Package versions:**
- core: 3.14.1
- two: 3.14.2
- ui: 3.14.2
- vitePlugin: 3.14.1

**Additional context**
Chrome vs Firefox Example (Exact Same Project):
![image](https://github.com/motion-canvas/motion-canvas/assets/65428672/6f8222dc-4379-4cfb-8748-64f81f8a4fd5)

**Comment by aarthificial** [comment]
This is an internal bug in Firefox:
https://bugzilla.mozilla.org/show_bug.cgi?id=1851963

They closed the issue two days ago and the fix will probably land in Firefox 124.0
